{
 "title": "Lifecycle Manager & Module Manager",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Lifecycle Manager Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"operator-controller-manager-metrics-service\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"operator-controller-manager-metrics-service\", code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"operator-controller-manager-metrics-service\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"operator-controller-manager-metrics-service\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Module Manager Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"manifest-operator-manager-metrics-service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Module Manager CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"manifest-operator-manager-metrics-service\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Module Manager Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"manifest-operator-manager-metrics-service\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"manifest-operator-manager-metrics-service\", code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"manifest-operator-manager-metrics-service\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"manifest-operator-ctrlman-metrics-service\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Lifecycle Manager Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"operator-controller-manager-metrics-service\"}",
     "legendFormat": "Lifecycle Manager"
    }
   ]
  },
  {
   "title": "Lifecycle Manager CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"operator-controller-manager-metrics-service\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Reconcile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Module Manager Controller Runtime Reconcile Success",
   "type": "timeseries",
   "description": "Total number of successfully reconciliations per controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"manifest\", result=\"requeue\"}[$__rate_interval])) by (controller)",
     "legendFormat": "requeue"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"manifest\", result=\"requeue_after\"}[$__rate_interval])) by (controller)",
     "legendFormat": "requeue_after"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"manifest\", result=\"success\"}[$__rate_interval])) by (controller)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Lifecycle Manager Controller Runtime Reconcile Success",
   "type": "timeseries",
   "description": "Total number of successfully reconciliations per controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"kyma\", result=\"requeue\"}[$__rate_interval])) by (controller)",
     "legendFormat": "requeue"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"kyma\", result=\"requeue_after\"}[$__rate_interval])) by (controller)",
     "legendFormat": "requeue_after"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"kyma\", result=\"success\"}[$__rate_interval])) by (controller)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Operator Controller Runtime Reconcile Errors",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{controller=\"kyma\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{controller=\"manifest\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Duration",
   "type": "graph",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_sum{name=\"manifest\"}[$__rate_interval])\n/\nrate(controller_runtime_reconcile_time_seconds_count{name=\"manifest\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_sum{name=\"kyma\"}[$__rate_interval])\n/\nrate(controller_runtime_reconcile_time_seconds_count{name=\"kyma\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Max Workers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (controller_runtime_max_concurrent_reconciles{controller=\"kyma\"})",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum by (controller) (controller_runtime_max_concurrent_reconciles{controller=\"manifest\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "description": "Number of currently used workers per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{controller=\"kyma\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "controller_runtime_active_workers{controller=\"manifest\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Workqueue Longest running processor seconds",
   "type": "timeseries",
   "description": "How many seconds has the longest running processor for workqueue been running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{job=\"operator-controller-manager-metrics-service\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "workqueue_longest_running_processor_seconds{job=\"manifest-operator-manager-metrics-service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Workqueue Unfinished Work Seconds",
   "type": "timeseries",
   "description": "How many seconds of work has been done that is in progress and hasn’t been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.\nworkqueue_longest_running_processor_seconds\tGauge\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{job=\"operator-controller-manager-metrics-service\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "workqueue_unfinished_work_seconds{job=\"manifest-operator-manager-metrics-service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Work Queue Processing Latency",
   "type": "graph",
   "description": "How long in seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  rate(workqueue_queue_duration_seconds_sum{name=\"manifest\"}[$__rate_interval])\n/\n  rate(workqueue_queue_duration_seconds_count{name=\"manifest\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "  rate(workqueue_queue_duration_seconds_sum{name=\"kyma\"}[$__rate_interval])\n/\n  rate(workqueue_queue_duration_seconds_count{name=\"kyma\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Processing Duration",
   "type": "graph",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{name=\"manifest\"}[$__rate_interval])\n/\nrate(workqueue_work_duration_seconds_count{name=\"manifest\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{name=\"kyma\"}[$__rate_interval])\n/\nrate(workqueue_work_duration_seconds_count{name=\"kyma\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "description": "The number of actions waiting in the queue to be performed.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=\"manifest\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "workqueue_depth{name=\"kyma\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{name=\"manifest\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(workqueue_adds_total{name=\"kyma\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}