/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// ACMEExternalAccountBindingApplyConfiguration represents a declarative configuration of the ACMEExternalAccountBinding type for use
// with apply.
//
// ACMEExternalAccountBinding is a reference to a CA external account of the ACME server.
type ACMEExternalAccountBindingApplyConfiguration struct {
	// keyID is the ID of the CA key that the External Account is bound to.
	KeyID *string `json:"keyID,omitempty"`
	// keySecretRef is the secret ref to the
	// Secret which holds the symmetric MAC key of the External Account Binding with data key 'hmacKey'.
	// The secret key stored in the Secret **must** be un-padded, base64 URL
	// encoded data.
	KeySecretRef *v1.SecretReferenceApplyConfiguration `json:"keySecretRef,omitempty"`
}

// ACMEExternalAccountBindingApplyConfiguration constructs a declarative configuration of the ACMEExternalAccountBinding type for use with
// apply.
func ACMEExternalAccountBinding() *ACMEExternalAccountBindingApplyConfiguration {
	return &ACMEExternalAccountBindingApplyConfiguration{}
}

// WithKeyID sets the KeyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyID field is set to the value of the last call.
func (b *ACMEExternalAccountBindingApplyConfiguration) WithKeyID(value string) *ACMEExternalAccountBindingApplyConfiguration {
	b.KeyID = &value
	return b
}

// WithKeySecretRef sets the KeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeySecretRef field is set to the value of the last call.
func (b *ACMEExternalAccountBindingApplyConfiguration) WithKeySecretRef(value *v1.SecretReferenceApplyConfiguration) *ACMEExternalAccountBindingApplyConfiguration {
	b.KeySecretRef = value
	return b
}
