/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DNSSelectionApplyConfiguration represents a declarative configuration of the DNSSelection type for use
// with apply.
//
// DNSSelection is a restriction on the domains to be allowed or forbidden for certificate requests
type DNSSelectionApplyConfiguration struct {
	// Include are domain names for which certificate requests are allowed (including any subdomains)
	Include []string `json:"include,omitempty"`
	// Exclude are domain names for which certificate requests are forbidden (including any subdomains)
	Exclude []string `json:"exclude,omitempty"`
}

// DNSSelectionApplyConfiguration constructs a declarative configuration of the DNSSelection type for use with
// apply.
func DNSSelection() *DNSSelectionApplyConfiguration {
	return &DNSSelectionApplyConfiguration{}
}

// WithInclude adds the given value to the Include field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Include field.
func (b *DNSSelectionApplyConfiguration) WithInclude(values ...string) *DNSSelectionApplyConfiguration {
	for i := range values {
		b.Include = append(b.Include, values[i])
	}
	return b
}

// WithExclude adds the given value to the Exclude field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Exclude field.
func (b *DNSSelectionApplyConfiguration) WithExclude(values ...string) *DNSSelectionApplyConfiguration {
	for i := range values {
		b.Exclude = append(b.Exclude, values[i])
	}
	return b
}
