/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// IssuerStatusApplyConfiguration represents a declarative configuration of the IssuerStatus type for use
// with apply.
//
// IssuerStatus is the status of the issuer.
type IssuerStatusApplyConfiguration struct {
	// ObservedGeneration is the observed generation of the spec.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// State is either empty, 'Pending', 'Error', or 'Ready'.
	State *string `json:"state,omitempty"`
	// Message is the status or error message.
	Message *string `json:"message,omitempty"`
	// Type is the issuer type. Currently only 'acme', 'ca' and 'selfSigned' are supported.
	Type *string `json:"type,omitempty"`
	// ACME is the ACME specific status.
	ACME *runtime.RawExtension `json:"acme,omitempty"`
	// CA is the CA specific status.
	CA *runtime.RawExtension `json:"ca,omitempty"`
	// RequestsPerDayQuota is the actual maximum number of certificate requests per days allowed for this issuer
	RequestsPerDayQuota *int `json:"requestsPerDayQuota,omitempty"`
}

// IssuerStatusApplyConfiguration constructs a declarative configuration of the IssuerStatus type for use with
// apply.
func IssuerStatus() *IssuerStatusApplyConfiguration {
	return &IssuerStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *IssuerStatusApplyConfiguration) WithObservedGeneration(value int64) *IssuerStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *IssuerStatusApplyConfiguration) WithState(value string) *IssuerStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *IssuerStatusApplyConfiguration) WithMessage(value string) *IssuerStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *IssuerStatusApplyConfiguration) WithType(value string) *IssuerStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithACME sets the ACME field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ACME field is set to the value of the last call.
func (b *IssuerStatusApplyConfiguration) WithACME(value runtime.RawExtension) *IssuerStatusApplyConfiguration {
	b.ACME = &value
	return b
}

// WithCA sets the CA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CA field is set to the value of the last call.
func (b *IssuerStatusApplyConfiguration) WithCA(value runtime.RawExtension) *IssuerStatusApplyConfiguration {
	b.CA = &value
	return b
}

// WithRequestsPerDayQuota sets the RequestsPerDayQuota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestsPerDayQuota field is set to the value of the last call.
func (b *IssuerStatusApplyConfiguration) WithRequestsPerDayQuota(value int) *IssuerStatusApplyConfiguration {
	b.RequestsPerDayQuota = &value
	return b
}
