/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	certv1alpha1 "github.com/gardener/cert-management/pkg/apis/cert/v1alpha1"
)

// IssuerSpecApplyConfiguration represents a declarative configuration of the IssuerSpec type for use
// with apply.
//
// IssuerSpec is the spec of the issuer.
type IssuerSpecApplyConfiguration struct {
	// ACME is the ACME protocol specific spec.
	ACME *ACMESpecApplyConfiguration `json:"acme,omitempty"`
	// CA is the CA specific spec.
	CA *CASpecApplyConfiguration `json:"ca,omitempty"`
	// SelfSigned is the self signed specific spec.
	SelfSigned *certv1alpha1.SelfSignedSpec `json:"selfSigned,omitempty"`
	// RequestsPerDayQuota is the maximum number of certificate requests per days allowed for this issuer
	RequestsPerDayQuota *int `json:"requestsPerDayQuota,omitempty"`
}

// IssuerSpecApplyConfiguration constructs a declarative configuration of the IssuerSpec type for use with
// apply.
func IssuerSpec() *IssuerSpecApplyConfiguration {
	return &IssuerSpecApplyConfiguration{}
}

// WithACME sets the ACME field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ACME field is set to the value of the last call.
func (b *IssuerSpecApplyConfiguration) WithACME(value *ACMESpecApplyConfiguration) *IssuerSpecApplyConfiguration {
	b.ACME = value
	return b
}

// WithCA sets the CA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CA field is set to the value of the last call.
func (b *IssuerSpecApplyConfiguration) WithCA(value *CASpecApplyConfiguration) *IssuerSpecApplyConfiguration {
	b.CA = value
	return b
}

// WithSelfSigned sets the SelfSigned field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelfSigned field is set to the value of the last call.
func (b *IssuerSpecApplyConfiguration) WithSelfSigned(value certv1alpha1.SelfSignedSpec) *IssuerSpecApplyConfiguration {
	b.SelfSigned = &value
	return b
}

// WithRequestsPerDayQuota sets the RequestsPerDayQuota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestsPerDayQuota field is set to the value of the last call.
func (b *IssuerSpecApplyConfiguration) WithRequestsPerDayQuota(value int) *IssuerSpecApplyConfiguration {
	b.RequestsPerDayQuota = &value
	return b
}
