{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lifecycle-manager.serviceAccountName" . }}
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.serviceAccount.gcp.iamName }}
  annotations:
    {{- if .Values.serviceAccount.gcp.iamName }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcp.iamName | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
# Base permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.managerName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  {{ .Files.Get "files/rbac-rules/klm-manager-rules.yaml" | nindent 2 }}
---
# CRD permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.managerCRDName" . }}
rules:
  {{ .Files.Get "files/rbac-rules/klm-manager-rules-crd.yaml" | nindent 2 }}
---
# Leader election permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.leaderElectionName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  {{ .Files.Get "files/rbac-rules/klm-leader-election-rules.yaml" | nindent 2 }}
---
# Certmanager permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.certmanager" . }}
  namespace: istio-system
rules:
  {{- include "lifecycle-manager.watcher.rules" . | nindent 2 }}
---
# CRD Rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.managerCRDName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lifecycle-manager.role.managerCRDName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lifecycle-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
# Base Rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.managerName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lifecycle-manager.role.managerName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lifecycle-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
# Certmanager Rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.certmanager" . }}
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lifecycle-manager.role.certmanager" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lifecycle-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
# Leader election rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "lifecycle-manager.labels" . | nindent 4 }}
  name: {{ include "lifecycle-manager.role.leaderElectionName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lifecycle-manager.role.leaderElectionName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lifecycle-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
