// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/applyconfigurations/api/v1beta2"
	internal "github.com/kyma-project/lifecycle-manager/api/applyconfigurations/internal"
	v1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=operator.kyma-project.io, Version=v1beta2
	case v1beta2.SchemeGroupVersion.WithKind("ChannelVersionAssignment"):
		return &apiv1beta2.ChannelVersionAssignmentApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("CustomStateCheck"):
		return &apiv1beta2.CustomStateCheckApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ImageSpec"):
		return &apiv1beta2.ImageSpecApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("InstallInfo"):
		return &apiv1beta2.InstallInfoApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("Manager"):
		return &apiv1beta2.ManagerApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("Mandatory"):
		return &apiv1beta2.MandatoryApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("Manifest"):
		return &apiv1beta2.ManifestApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ManifestSpec"):
		return &apiv1beta2.ManifestSpecApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ModuleIcon"):
		return &apiv1beta2.ModuleIconApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ModuleInfo"):
		return &apiv1beta2.ModuleInfoApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ModuleReleaseMeta"):
		return &apiv1beta2.ModuleReleaseMetaApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ModuleReleaseMetaSpec"):
		return &apiv1beta2.ModuleReleaseMetaSpecApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ModuleTemplate"):
		return &apiv1beta2.ModuleTemplateApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("ModuleTemplateSpec"):
		return &apiv1beta2.ModuleTemplateSpecApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("Resource"):
		return &apiv1beta2.ResourceApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
