{
 "title": "Lifecycle Manager Mandatory Modules",
 "description": "This dashboard shows an overview of all the mandatory modules on the SKR.",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Warden", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Warden Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (shoot) (runtime:apiserver:available))",
     "legendFormat": "SKR Count"
    },
    {
     "expr": "count(group by (shoot) (kube_deployment_spec_replicas{deployment=~\"warden-.*\"})) / count(group by (shoot) (runtime:apiserver:available)) * 100",
     "legendFormat": "SKR(s) with Warden Deployment"
    },
    {
     "expr": "count(group by (shoot) (kube_deployment_spec_replicas{deployment=~\"warden-.*\"}))",
     "legendFormat": "SKR Warden Deployment Count"
    }
   ]
  },
  {
   "title": "Warden Images on Shoots",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (image) (group by (image, shoot) (kube_pod_container_info{namespace=\"kyma-system\", pod=~\"warden-.*\", container=~\"(admission)|(operator)\"}))",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Unready Warden Deployments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (shoot) (kube_deployment_status_replicas_unavailable{deployment=~\"warden-.*\"})) OR on() vector(0)",
     "legendFormat": "Unready Warden Deployments"
    }
   ]
  }
 ]
}