{
 "title": "Lifecycle Manager Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lifecycle Manager Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"klm-controller-manager-metrics\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"klm-controller-manager-metrics\", code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"klm-controller-manager-metrics\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"klm-controller-manager-metrics\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Lifecycle Manager Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"klm-controller-manager-metrics\"}",
     "legendFormat": "Lifecycle Manager"
    }
   ]
  },
  {
   "title": "Lifecycle Manager CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Reconcile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Lifecycle Manager Controller Runtime Reconcile Success",
   "type": "timeseries",
   "description": "Rate of successfully reconciliations per controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{controller=~\"kyma|watcher|manifest|mandatory-module-installation|mandatory-module-deletion\",job=\"klm-controller-manager-metrics\", result=~\"success|requeue_after\"}[$__rate_interval])",
     "legendFormat": "{{controller }} - {{result}}"
    }
   ]
  },
  {
   "title": "Operator Controller Runtime Reconcile Errors",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{controller=~\"kyma|watcher|manifest|mandatory-module-installation|mandatory-module-deletion\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Kyma Requeue Reason",
   "type": "graph",
   "description": "How many times Kyma was requeued due to specific reasons",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lifecycle_mgr_requeue_reason_total)[$__rate_interval]",
     "legendFormat": "{{requeue_reason}} - {{requeue_type}}"
    }
   ]
  },
  {
   "title": "Reconcile Duration",
   "type": "graph",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_sum{controller=\"manifest\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])\n/\nrate(controller_runtime_reconcile_time_seconds_count{controller=\"manifest\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_sum{controller=\"kyma\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])\n/\nrate(controller_runtime_reconcile_time_seconds_count{controller=\"kyma\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Max Workers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (controller_runtime_max_concurrent_reconciles{container=\"manager\",controller=\"kyma\"})",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum by (controller) (controller_runtime_max_concurrent_reconciles{container=\"manager\",controller=\"manifest\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "description": "Number of currently used workers per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{controller=\"kyma\",job=\"klm-controller-manager-metrics\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "controller_runtime_active_workers{controller=\"manifest\",job=\"klm-controller-manager-metrics\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Workqueue Longest running processor seconds",
   "type": "timeseries",
   "description": "How many seconds has the longest running processor for workqueue been running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{job=\"klm-controller-manager-metrics\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Workqueue Unfinished Work Seconds",
   "type": "timeseries",
   "description": "How many seconds of work has been done that is in progress and hasn’t been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.\nworkqueue_longest_running_processor_seconds\tGauge\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{job=\"klm-controller-manager-metrics\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Work Queue Processing Latency",
   "type": "graph",
   "description": "How long in seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  rate(workqueue_queue_duration_seconds_sum{name=\"manifest\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])\n/\n  rate(workqueue_queue_duration_seconds_count{name=\"manifest\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "  rate(workqueue_queue_duration_seconds_sum{name=\"kyma\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])\n/\n  rate(workqueue_queue_duration_seconds_count{name=\"kyma\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Processing Duration",
   "type": "graph",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{name=\"manifest\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])\n/\nrate(workqueue_work_duration_seconds_count{name=\"manifest\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{name=\"kyma\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])\n/\nrate(workqueue_work_duration_seconds_count{name=\"kyma\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "description": "The number of actions waiting in the queue to be performed.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=\"manifest\",job=\"klm-controller-manager-metrics\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "workqueue_depth{name=\"kyma\",job=\"klm-controller-manager-metrics\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{name=\"manifest\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(workqueue_adds_total{name=\"kyma\",job=\"klm-controller-manager-metrics\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Certificate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Self-signed Certificate Not Renew",
   "type": "table",
   "description": "Indicates the self-signed Certificate of related Kyma is not renewed yet",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "lifecycle_mgr_self_signed_cert_not_renew{service=\"klm-controller-manager-metrics\"}",
     "legendFormat": "{{kyma_name}}"
    }
   ]
  },
  { "title": "Maintenance Windows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Maintenance Window Configuration Read Status",
   "type": "stat",
   "description": "Indicates whether the KLM successfully read the maintenance policy file from the mounted ConfigMap.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lifecycle_mgr_maintenance_window_config_read_success",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}