{
 "title": "Lifecycle Manager Kyma Status",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Kyma State Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kyma State Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lifecycle_mgr_kyma_state{state=\"Ready\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(lifecycle_mgr_kyma_state{state=\"Deleting\"})",
     "legendFormat": "Deleting"
    },
    {
     "expr": "sum(lifecycle_mgr_kyma_state{state=\"Processing\"})",
     "legendFormat": "Processing"
    },
    {
     "expr": "sum(lifecycle_mgr_kyma_state{state=\"Error\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(lifecycle_mgr_kyma_state{state=\"Warning\"})",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Module State Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lifecycle_mgr_module_state{state=\"Ready\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(lifecycle_mgr_module_state{state=\"Deleting\"})",
     "legendFormat": "Deleting"
    },
    {
     "expr": "sum(lifecycle_mgr_module_state{state=\"Processing\"})",
     "legendFormat": "Processing"
    },
    {
     "expr": "sum(lifecycle_mgr_module_state{state=\"Error\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(lifecycle_mgr_module_state{state=\"Warning\"})",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Mandatory Module State Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lifecycle_mgr_mandatory_module_state{state=\"Ready\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(lifecycle_mgr_mandatory_module_state{state=\"Deleting\"})",
     "legendFormat": "Deleting"
    },
    {
     "expr": "sum(lifecycle_mgr_mandatory_module_state{state=\"Processing\"})",
     "legendFormat": "Processing"
    },
    {
     "expr": "sum(lifecycle_mgr_mandatory_module_state{state=\"Error\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(lifecycle_mgr_mandatory_module_state{state=\"Warning\"})",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Mandatory Modules Count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifecycle_mgr_mandatory_modules)"
    }
   ]
  }
 ]
}