{
 "title": "Lifecycle Manager Watcher Components",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (shoot) (runtime:apiserver:available))",
     "legendFormat": "SKR Count"
    },
    {
     "expr": "count(group by (shoot) (kube_deployment_spec_replicas{deployment=\"skr-webhook\"})) / count(group by (shoot) (runtime:apiserver:available)) * 100",
     "legendFormat": "SKR's with SKR Watcher Deployment"
    },
    {
     "expr": "count(group by (shoot) (kube_deployment_spec_replicas{deployment=\"skr-webhook\"}))",
     "legendFormat": "SKR Watcher Deployment Count"
    }
   ]
  },
  {
   "title": "Images on Shoots",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (image) (group by (shoot, image) (kube_pod_container_info{namespace=\"kyma-system\",pod=~\"skr-webhook-.*\"}))",
     "legendFormat": "Shoots"
    }
   ]
  },
  {
   "title": "Unready SKR Watcher Deployments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (shoot) (kube_deployment_status_replicas_unavailable{deployment=\"skr-webhook\"})) OR on() vector(0)",
     "legendFormat": "Unready SKR Watcher Deployments"
    }
   ]
  },
  { "title": "Listener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(watcher_listener_requests_total[$__rate_interval])",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "watcher_listener_request_duration",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Pending Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "watcher_listener_inflight_requests",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Failed Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(watcher_listener_request_errors_total[$__rate_interval])",
     "legendFormat": "Total Failed Requests"
    },
    {
     "expr": "rate(watcher_listener_exceeding_size_limit_requests_total[$__rate_interval])",
     "legendFormat": "Failed Requests due to Size Limit"
    },
    {
     "expr": "rate(watcher_listener_failed_verification_requests_total[$__rate_interval])",
     "legendFormat": "Failed Requests due to Verification Error"
    }
   ]
  },
  { "title": "SKR-Webhook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "AdmissionRequest Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "watcher_request_duration" }
   ]
  },
  {
   "title": "AdmissionRequest Error Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(watcher_admission_request_error_total)[5m]"
    }
   ]
  },
  {
   "title": "AdmissionRequests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(watcher_admission_request_total[5m])"
    }
   ]
  },
  {
   "title": "Failed KCP Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(watcher_failed_kcp_total[5m])"
    }
   ]
  },
  {
   "title": "KCP Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(watcher_kcp_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Requests Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(watcher_admission_request_total[5m]) / rate(watcher_kcp_requests_total[5m])"
    }
   ]
  }
 ]
}