/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	operatorkymaprojectiov1alpha1 "github.com/kyma-project/lifecycle-manager/api/v1alpha1"
	"github.com/kyma-project/lifecycle-manager/pkg/client/clientset/versioned"
	"github.com/kyma-project/lifecycle-manager/pkg/client/informers/externalversions/internalinterfaces"
	"github.com/kyma-project/lifecycle-manager/pkg/client/listers/operator.kyma-project.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"
)

// ModuleTemplateInformer provides access to a shared informer and lister for
// ModuleTemplates.
type ModuleTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ModuleTemplateLister
}

type moduleTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewModuleTemplateInformer constructs a new informer for ModuleTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewModuleTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredModuleTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredModuleTemplateInformer constructs a new informer for ModuleTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredModuleTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().ModuleTemplates(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().ModuleTemplates(namespace).Watch(context.TODO(), options)
			},
		},
		&operatorkymaprojectiov1alpha1.ModuleTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *moduleTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredModuleTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *moduleTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorkymaprojectiov1alpha1.ModuleTemplate{}, f.defaultInformer)
}

func (f *moduleTemplateInformer) Lister() v1alpha1.ModuleTemplateLister {
	return v1alpha1.NewModuleTemplateLister(f.Informer().GetIndexer())
}
