// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ChannelVersionAssignmentApplyConfiguration represents a declarative configuration of the ChannelVersionAssignment type for use
// with apply.
type ChannelVersionAssignmentApplyConfiguration struct {
	Channel *string `json:"channel,omitempty"`
	Version *string `json:"version,omitempty"`
}

// ChannelVersionAssignmentApplyConfiguration constructs a declarative configuration of the ChannelVersionAssignment type for use with
// apply.
func ChannelVersionAssignment() *ChannelVersionAssignmentApplyConfiguration {
	return &ChannelVersionAssignmentApplyConfiguration{}
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *ChannelVersionAssignmentApplyConfiguration) WithChannel(value string) *ChannelVersionAssignmentApplyConfiguration {
	b.Channel = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ChannelVersionAssignmentApplyConfiguration) WithVersion(value string) *ChannelVersionAssignmentApplyConfiguration {
	b.Version = &value
	return b
}
