/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	shared "github.com/kyma-project/lifecycle-manager/api/shared"
)

// CustomStateCheckApplyConfiguration represents a declarative configuration of the CustomStateCheck type for use
// with apply.
type CustomStateCheckApplyConfiguration struct {
	// JSONPath specifies the JSON path to the state variable in the Module CR
	JSONPath *string `json:"jsonPath,omitempty"`
	// Value is the value at the JSONPath for which the Module CR state should map with MappedState
	Value *string `json:"value,omitempty"`
	// MappedState is the Kyma CR State
	MappedState *shared.State `json:"mappedState,omitempty"`
}

// CustomStateCheckApplyConfiguration constructs a declarative configuration of the CustomStateCheck type for use with
// apply.
func CustomStateCheck() *CustomStateCheckApplyConfiguration {
	return &CustomStateCheckApplyConfiguration{}
}

// WithJSONPath sets the JSONPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JSONPath field is set to the value of the last call.
func (b *CustomStateCheckApplyConfiguration) WithJSONPath(value string) *CustomStateCheckApplyConfiguration {
	b.JSONPath = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *CustomStateCheckApplyConfiguration) WithValue(value string) *CustomStateCheckApplyConfiguration {
	b.Value = &value
	return b
}

// WithMappedState sets the MappedState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MappedState field is set to the value of the last call.
func (b *CustomStateCheckApplyConfiguration) WithMappedState(value shared.State) *CustomStateCheckApplyConfiguration {
	b.MappedState = &value
	return b
}
