// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	shared "github.com/kyma-project/lifecycle-manager/api/shared"
)

// CustomStateCheckApplyConfiguration represents a declarative configuration of the CustomStateCheck type for use
// with apply.
type CustomStateCheckApplyConfiguration struct {
	JSONPath    *string       `json:"jsonPath,omitempty"`
	Value       *string       `json:"value,omitempty"`
	MappedState *shared.State `json:"mappedState,omitempty"`
}

// CustomStateCheckApplyConfiguration constructs a declarative configuration of the CustomStateCheck type for use with
// apply.
func CustomStateCheck() *CustomStateCheckApplyConfiguration {
	return &CustomStateCheckApplyConfiguration{}
}

// WithJSONPath sets the JSONPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JSONPath field is set to the value of the last call.
func (b *CustomStateCheckApplyConfiguration) WithJSONPath(value string) *CustomStateCheckApplyConfiguration {
	b.JSONPath = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *CustomStateCheckApplyConfiguration) WithValue(value string) *CustomStateCheckApplyConfiguration {
	b.Value = &value
	return b
}

// WithMappedState sets the MappedState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MappedState field is set to the value of the last call.
func (b *CustomStateCheckApplyConfiguration) WithMappedState(value shared.State) *CustomStateCheckApplyConfiguration {
	b.MappedState = &value
	return b
}
