/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ImageSpecApplyConfiguration represents a declarative configuration of the ImageSpec type for use
// with apply.
//
// ImageSpec defines OCI Image specifications.
type ImageSpecApplyConfiguration struct {
	// Repo defines the Image repo
	Repo *string `json:"repo,omitempty"`
	// Name defines the Image name
	Name *string `json:"name,omitempty"`
	// Ref is either a sha value, tag or version
	Ref *string `json:"ref,omitempty"`
	// Type specifies the type of installation specification
	// that could be provided as part of a custom resource.
	// This time is used in codec to successfully decode from raw extensions.
	Type *apiv1beta2.RefTypeMetadata `json:"type,omitempty"`
	// Deprecated: Field will be removed soon and is not supported anymore.
	CredSecretSelector *v1.LabelSelectorApplyConfiguration `json:"credSecretSelector,omitempty"`
}

// ImageSpecApplyConfiguration constructs a declarative configuration of the ImageSpec type for use with
// apply.
func ImageSpec() *ImageSpecApplyConfiguration {
	return &ImageSpecApplyConfiguration{}
}

// WithRepo sets the Repo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repo field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithRepo(value string) *ImageSpecApplyConfiguration {
	b.Repo = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithName(value string) *ImageSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithRef(value string) *ImageSpecApplyConfiguration {
	b.Ref = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithType(value apiv1beta2.RefTypeMetadata) *ImageSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithCredSecretSelector sets the CredSecretSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredSecretSelector field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithCredSecretSelector(value *v1.LabelSelectorApplyConfiguration) *ImageSpecApplyConfiguration {
	b.CredSecretSelector = value
	return b
}
