// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ImageSpecApplyConfiguration represents a declarative configuration of the ImageSpec type for use
// with apply.
type ImageSpecApplyConfiguration struct {
	Repo               *string                             `json:"repo,omitempty"`
	Name               *string                             `json:"name,omitempty"`
	Ref                *string                             `json:"ref,omitempty"`
	Type               *apiv1beta2.RefTypeMetadata         `json:"type,omitempty"`
	CredSecretSelector *v1.LabelSelectorApplyConfiguration `json:"credSecretSelector,omitempty"`
}

// ImageSpecApplyConfiguration constructs a declarative configuration of the ImageSpec type for use with
// apply.
func ImageSpec() *ImageSpecApplyConfiguration {
	return &ImageSpecApplyConfiguration{}
}

// WithRepo sets the Repo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repo field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithRepo(value string) *ImageSpecApplyConfiguration {
	b.Repo = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithName(value string) *ImageSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithRef(value string) *ImageSpecApplyConfiguration {
	b.Ref = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithType(value apiv1beta2.RefTypeMetadata) *ImageSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithCredSecretSelector sets the CredSecretSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredSecretSelector field is set to the value of the last call.
func (b *ImageSpecApplyConfiguration) WithCredSecretSelector(value *v1.LabelSelectorApplyConfiguration) *ImageSpecApplyConfiguration {
	b.CredSecretSelector = value
	return b
}
