/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// InstallInfoApplyConfiguration represents a declarative configuration of the InstallInfo type for use
// with apply.
//
// InstallInfo defines installation information.
type InstallInfoApplyConfiguration struct {
	// Source in the ImageSpec format
	Source *runtime.RawExtension `json:"source,omitempty"`
	// Name specifies a unique install name for Manifest
	Name *string `json:"name,omitempty"`
}

// InstallInfoApplyConfiguration constructs a declarative configuration of the InstallInfo type for use with
// apply.
func InstallInfo() *InstallInfoApplyConfiguration {
	return &InstallInfoApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *InstallInfoApplyConfiguration) WithSource(value runtime.RawExtension) *InstallInfoApplyConfiguration {
	b.Source = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InstallInfoApplyConfiguration) WithName(value string) *InstallInfoApplyConfiguration {
	b.Name = &value
	return b
}
