// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// InstallInfoApplyConfiguration represents a declarative configuration of the InstallInfo type for use
// with apply.
type InstallInfoApplyConfiguration struct {
	Source *runtime.RawExtension `json:"source,omitempty"`
	Name   *string               `json:"name,omitempty"`
}

// InstallInfoApplyConfiguration constructs a declarative configuration of the InstallInfo type for use with
// apply.
func InstallInfo() *InstallInfoApplyConfiguration {
	return &InstallInfoApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *InstallInfoApplyConfiguration) WithSource(value runtime.RawExtension) *InstallInfoApplyConfiguration {
	b.Source = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InstallInfoApplyConfiguration) WithName(value string) *InstallInfoApplyConfiguration {
	b.Name = &value
	return b
}
