/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// KymaSpecApplyConfiguration represents a declarative configuration of the KymaSpec type for use
// with apply.
//
// KymaSpec defines the desired state of Kyma.
type KymaSpecApplyConfiguration struct {
	// Channel specifies the desired Channel of the Installation, usually targeting different module versions.
	Channel *string `json:"channel,omitempty"`
	// SkipMaintenanceWindows indicates whether module upgrades that require downtime
	// should bypass the defined Maintenance Windows and be applied immediately.
	SkipMaintenanceWindows *bool `json:"skipMaintenanceWindows,omitempty"`
	// Modules specifies the list of modules to be installed
	Modules []ModuleApplyConfiguration `json:"modules,omitempty"`
}

// KymaSpecApplyConfiguration constructs a declarative configuration of the KymaSpec type for use with
// apply.
func KymaSpec() *KymaSpecApplyConfiguration {
	return &KymaSpecApplyConfiguration{}
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *KymaSpecApplyConfiguration) WithChannel(value string) *KymaSpecApplyConfiguration {
	b.Channel = &value
	return b
}

// WithSkipMaintenanceWindows sets the SkipMaintenanceWindows field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipMaintenanceWindows field is set to the value of the last call.
func (b *KymaSpecApplyConfiguration) WithSkipMaintenanceWindows(value bool) *KymaSpecApplyConfiguration {
	b.SkipMaintenanceWindows = &value
	return b
}

// WithModules adds the given value to the Modules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Modules field.
func (b *KymaSpecApplyConfiguration) WithModules(values ...*ModuleApplyConfiguration) *KymaSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithModules")
		}
		b.Modules = append(b.Modules, *values[i])
	}
	return b
}
