/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	shared "github.com/kyma-project/lifecycle-manager/api/shared"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// KymaStatusApplyConfiguration represents a declarative configuration of the KymaStatus type for use
// with apply.
//
// KymaStatus defines the observed state of Kyma.
type KymaStatusApplyConfiguration struct {
	LastOperation *shared.LastOperation `json:"lastOperation,omitempty"`
	// State signifies current state of Kyma.
	// Value can be one of ("Ready", "Processing", "Warning", "Error", "Deleting").
	// Note: The requeue interval in Error State is subject to rate limiting.
	State *shared.State `json:"state,omitempty"`
	// List of status conditions to indicate the status of a ServiceInstance.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Contains essential information about the current deployed module
	Modules []ModuleStatusApplyConfiguration `json:"modules,omitempty"`
	// Active Channel
	ActiveChannel *string `json:"activeChannel,omitempty"`
}

// KymaStatusApplyConfiguration constructs a declarative configuration of the KymaStatus type for use with
// apply.
func KymaStatus() *KymaStatusApplyConfiguration {
	return &KymaStatusApplyConfiguration{}
}

// WithLastOperation sets the LastOperation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastOperation field is set to the value of the last call.
func (b *KymaStatusApplyConfiguration) WithLastOperation(value shared.LastOperation) *KymaStatusApplyConfiguration {
	b.LastOperation = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *KymaStatusApplyConfiguration) WithState(value shared.State) *KymaStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *KymaStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *KymaStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithModules adds the given value to the Modules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Modules field.
func (b *KymaStatusApplyConfiguration) WithModules(values ...*ModuleStatusApplyConfiguration) *KymaStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithModules")
		}
		b.Modules = append(b.Modules, *values[i])
	}
	return b
}

// WithActiveChannel sets the ActiveChannel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveChannel field is set to the value of the last call.
func (b *KymaStatusApplyConfiguration) WithActiveChannel(value string) *KymaStatusApplyConfiguration {
	b.ActiveChannel = &value
	return b
}
