// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ManagerApplyConfiguration represents a declarative configuration of the Manager type for use
// with apply.
type ManagerApplyConfiguration struct {
	Group     *string `json:"group,omitempty"`
	Version   *string `json:"version,omitempty"`
	Kind      *string `json:"kind,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// ManagerApplyConfiguration constructs a declarative configuration of the Manager type for use with
// apply.
func Manager() *ManagerApplyConfiguration {
	return &ManagerApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithGroup(value string) *ManagerApplyConfiguration {
	b.Group = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithVersion(value string) *ManagerApplyConfiguration {
	b.Version = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithKind(value string) *ManagerApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithNamespace(value string) *ManagerApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithName(value string) *ManagerApplyConfiguration {
	b.Name = &value
	return b
}
