/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// ManagerApplyConfiguration represents a declarative configuration of the Manager type for use
// with apply.
//
// Manager defines the structure for the manager field in ModuleTemplateSpec.
type ManagerApplyConfiguration struct {
	// Group is the API group of the manager resource.
	Group *string `json:"group,omitempty"`
	// Version is the API version of the manager resource.
	Version *string `json:"version,omitempty"`
	// Kind is the kind of the manager resource.
	Kind *string `json:"kind,omitempty"`
	// Namespace is the namespace of the manager. It is optional.
	Namespace *string `json:"namespace,omitempty"`
	// Name is the name of the manager.
	Name *string `json:"name,omitempty"`
}

// ManagerApplyConfiguration constructs a declarative configuration of the Manager type for use with
// apply.
func Manager() *ManagerApplyConfiguration {
	return &ManagerApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithGroup(value string) *ManagerApplyConfiguration {
	b.Group = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithVersion(value string) *ManagerApplyConfiguration {
	b.Version = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithKind(value string) *ManagerApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithNamespace(value string) *ManagerApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ManagerApplyConfiguration) WithName(value string) *ManagerApplyConfiguration {
	b.Name = &value
	return b
}
