// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// MandatoryApplyConfiguration represents a declarative configuration of the Mandatory type for use
// with apply.
type MandatoryApplyConfiguration struct {
	Version *string `json:"version,omitempty"`
}

// MandatoryApplyConfiguration constructs a declarative configuration of the Mandatory type for use with
// apply.
func Mandatory() *MandatoryApplyConfiguration {
	return &MandatoryApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *MandatoryApplyConfiguration) WithVersion(value string) *MandatoryApplyConfiguration {
	b.Version = &value
	return b
}
