/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// ManifestSpecApplyConfiguration represents a declarative configuration of the ManifestSpec type for use
// with apply.
//
// ManifestSpec defines the desired state of Manifest.
type ManifestSpecApplyConfiguration struct {
	CustomResourcePolicy *apiv1beta2.CustomResourcePolicy `json:"customResourcePolicy,omitempty"`
	// Remote indicates if Manifest should be installed on a remote cluster
	Remote *bool `json:"remote,omitempty"`
	// Version specifies current Resource version
	Version *string `json:"version,omitempty"`
	// Config specifies OCI image configuration for Manifest
	Config *ImageSpecApplyConfiguration `json:"config,omitempty"`
	// Install specifies a list of installations for Manifest
	Install *InstallInfoApplyConfiguration `json:"install,omitempty"`
	// Resource specifies a resource to be watched for state updates
	Resource *unstructured.Unstructured `json:"resource,omitempty"`
	// LocalizedImages specifies a list of docker image references valid for the environment
	// where the Manifest is installed.
	// The list entries are corresponding to the images actually used in the K8s resources of the Kyma module.
	// If provided, when the Kyma Module is installed in the target cluster,
	// the "localized" image reference is used instead of the original one.
	LocalizedImages []string `json:"localizedImages,omitempty"`
	// Manager contains information for identifying a module's resource that can be used as indicator for the installation readiness of the module. Typically, this is the manager Deployment of the module. In exceptional cases, it may also be another resource.
	Manager *ManagerApplyConfiguration `json:"manager,omitempty"`
}

// ManifestSpecApplyConfiguration constructs a declarative configuration of the ManifestSpec type for use with
// apply.
func ManifestSpec() *ManifestSpecApplyConfiguration {
	return &ManifestSpecApplyConfiguration{}
}

// WithCustomResourcePolicy sets the CustomResourcePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomResourcePolicy field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithCustomResourcePolicy(value apiv1beta2.CustomResourcePolicy) *ManifestSpecApplyConfiguration {
	b.CustomResourcePolicy = &value
	return b
}

// WithRemote sets the Remote field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remote field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithRemote(value bool) *ManifestSpecApplyConfiguration {
	b.Remote = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithVersion(value string) *ManifestSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithConfig(value *ImageSpecApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithInstall sets the Install field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Install field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithInstall(value *InstallInfoApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Install = value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithResource(value unstructured.Unstructured) *ManifestSpecApplyConfiguration {
	b.Resource = &value
	return b
}

// WithLocalizedImages adds the given value to the LocalizedImages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LocalizedImages field.
func (b *ManifestSpecApplyConfiguration) WithLocalizedImages(values ...string) *ManifestSpecApplyConfiguration {
	for i := range values {
		b.LocalizedImages = append(b.LocalizedImages, values[i])
	}
	return b
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithManager(value *ManagerApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Manager = value
	return b
}
