// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// ManifestSpecApplyConfiguration represents a declarative configuration of the ManifestSpec type for use
// with apply.
type ManifestSpecApplyConfiguration struct {
	CustomResourcePolicy *apiv1beta2.CustomResourcePolicy `json:"customResourcePolicy,omitempty"`
	Remote               *bool                            `json:"remote,omitempty"`
	Version              *string                          `json:"version,omitempty"`
	Config               *ImageSpecApplyConfiguration     `json:"config,omitempty"`
	Install              *InstallInfoApplyConfiguration   `json:"install,omitempty"`
	Resource             *unstructured.Unstructured       `json:"resource,omitempty"`
	LocalizedImages      []string                         `json:"localizedImages,omitempty"`
	Manager              *ManagerApplyConfiguration       `json:"manager,omitempty"`
}

// ManifestSpecApplyConfiguration constructs a declarative configuration of the ManifestSpec type for use with
// apply.
func ManifestSpec() *ManifestSpecApplyConfiguration {
	return &ManifestSpecApplyConfiguration{}
}

// WithCustomResourcePolicy sets the CustomResourcePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomResourcePolicy field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithCustomResourcePolicy(value apiv1beta2.CustomResourcePolicy) *ManifestSpecApplyConfiguration {
	b.CustomResourcePolicy = &value
	return b
}

// WithRemote sets the Remote field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remote field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithRemote(value bool) *ManifestSpecApplyConfiguration {
	b.Remote = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithVersion(value string) *ManifestSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithConfig(value *ImageSpecApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithInstall sets the Install field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Install field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithInstall(value *InstallInfoApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Install = value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithResource(value unstructured.Unstructured) *ManifestSpecApplyConfiguration {
	b.Resource = &value
	return b
}

// WithLocalizedImages adds the given value to the LocalizedImages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LocalizedImages field.
func (b *ManifestSpecApplyConfiguration) WithLocalizedImages(values ...string) *ManifestSpecApplyConfiguration {
	for i := range values {
		b.LocalizedImages = append(b.LocalizedImages, values[i])
	}
	return b
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithManager(value *ManagerApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Manager = value
	return b
}
