/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

// ModuleIconApplyConfiguration represents a declarative configuration of the ModuleIcon type for use
// with apply.
type ModuleIconApplyConfiguration struct {
	// Name is the name of the icon.
	Name *string `json:"name,omitempty"`
	// Link is the link to the icon.
	Link *string `json:"link,omitempty"`
}

// ModuleIconApplyConfiguration constructs a declarative configuration of the ModuleIcon type for use with
// apply.
func ModuleIcon() *ModuleIconApplyConfiguration {
	return &ModuleIconApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModuleIconApplyConfiguration) WithName(value string) *ModuleIconApplyConfiguration {
	b.Name = &value
	return b
}

// WithLink sets the Link field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Link field is set to the value of the last call.
func (b *ModuleIconApplyConfiguration) WithLink(value string) *ModuleIconApplyConfiguration {
	b.Link = &value
	return b
}
