// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ModuleTemplateSpecApplyConfiguration represents a declarative configuration of the ModuleTemplateSpec type for use
// with apply.
type ModuleTemplateSpecApplyConfiguration struct {
	Channel             *string                        `json:"channel,omitempty"`
	Version             *string                        `json:"version,omitempty"`
	ModuleName          *string                        `json:"moduleName,omitempty"`
	Mandatory           *bool                          `json:"mandatory,omitempty"`
	Data                *unstructured.Unstructured     `json:"data,omitempty"`
	Descriptor          *runtime.RawExtension          `json:"descriptor,omitempty"`
	CustomStateCheck    []*apiv1beta2.CustomStateCheck `json:"customStateCheck,omitempty"`
	Resources           []ResourceApplyConfiguration   `json:"resources,omitempty"`
	Info                *ModuleInfoApplyConfiguration  `json:"info,omitempty"`
	AssociatedResources []v1.GroupVersionKind          `json:"associatedResources,omitempty"`
	Manager             *ManagerApplyConfiguration     `json:"manager,omitempty"`
	RequiresDowntime    *bool                          `json:"requiresDowntime,omitempty"`
}

// ModuleTemplateSpecApplyConfiguration constructs a declarative configuration of the ModuleTemplateSpec type for use with
// apply.
func ModuleTemplateSpec() *ModuleTemplateSpecApplyConfiguration {
	return &ModuleTemplateSpecApplyConfiguration{}
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithChannel(value string) *ModuleTemplateSpecApplyConfiguration {
	b.Channel = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithVersion(value string) *ModuleTemplateSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithModuleName sets the ModuleName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModuleName field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithModuleName(value string) *ModuleTemplateSpecApplyConfiguration {
	b.ModuleName = &value
	return b
}

// WithMandatory sets the Mandatory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mandatory field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithMandatory(value bool) *ModuleTemplateSpecApplyConfiguration {
	b.Mandatory = &value
	return b
}

// WithData sets the Data field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Data field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithData(value unstructured.Unstructured) *ModuleTemplateSpecApplyConfiguration {
	b.Data = &value
	return b
}

// WithDescriptor sets the Descriptor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Descriptor field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithDescriptor(value runtime.RawExtension) *ModuleTemplateSpecApplyConfiguration {
	b.Descriptor = &value
	return b
}

// WithCustomStateCheck adds the given value to the CustomStateCheck field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomStateCheck field.
func (b *ModuleTemplateSpecApplyConfiguration) WithCustomStateCheck(values ...**apiv1beta2.CustomStateCheck) *ModuleTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCustomStateCheck")
		}
		b.CustomStateCheck = append(b.CustomStateCheck, *values[i])
	}
	return b
}

// WithResources adds the given value to the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resources field.
func (b *ModuleTemplateSpecApplyConfiguration) WithResources(values ...*ResourceApplyConfiguration) *ModuleTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResources")
		}
		b.Resources = append(b.Resources, *values[i])
	}
	return b
}

// WithInfo sets the Info field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Info field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithInfo(value *ModuleInfoApplyConfiguration) *ModuleTemplateSpecApplyConfiguration {
	b.Info = value
	return b
}

// WithAssociatedResources adds the given value to the AssociatedResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AssociatedResources field.
func (b *ModuleTemplateSpecApplyConfiguration) WithAssociatedResources(values ...v1.GroupVersionKind) *ModuleTemplateSpecApplyConfiguration {
	for i := range values {
		b.AssociatedResources = append(b.AssociatedResources, values[i])
	}
	return b
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithManager(value *ManagerApplyConfiguration) *ModuleTemplateSpecApplyConfiguration {
	b.Manager = value
	return b
}

// WithRequiresDowntime sets the RequiresDowntime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiresDowntime field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithRequiresDowntime(value bool) *ModuleTemplateSpecApplyConfiguration {
	b.RequiresDowntime = &value
	return b
}
