/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
)

// ModuleApplyConfiguration represents a declarative configuration of the Module type for use
// with apply.
//
// Module defines the components to be installed.
type ModuleApplyConfiguration struct {
	CustomResourcePolicy *apiv1beta2.CustomResourcePolicy `json:"customResourcePolicy,omitempty"`
	// Name is a unique identifier of the module.
	// It is used to resolve a ModuleTemplate for creating a set of resources on the cluster.
	Name *string `json:"name,omitempty"`
	// ControllerName is able to set the controller used for reconciliation of the module. It can be used
	// together with Cache Configuration on the Operator responsible for the templated Modules to split
	// workload.
	ControllerName *string `json:"controller,omitempty"`
	// Channel is the desired channel of the Module. If this changes or is set, it will be used to resolve a new
	// ModuleTemplate based on the new resolved resources.
	Channel *string `json:"channel,omitempty"`
	// RemoteModuleTemplateRef is deprecated and will no longer have any functionality.
	// It will be removed in the upcoming API version.
	RemoteModuleTemplateRef *string `json:"remoteModuleTemplateRef,omitempty"`
	// Managed is determining whether the module is managed or not. If the module is unmanaged, the user is responsible
	// for the lifecycle of the module.
	Managed *bool `json:"managed,omitempty"`
}

// ModuleApplyConfiguration constructs a declarative configuration of the Module type for use with
// apply.
func Module() *ModuleApplyConfiguration {
	return &ModuleApplyConfiguration{}
}

// WithCustomResourcePolicy sets the CustomResourcePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomResourcePolicy field is set to the value of the last call.
func (b *ModuleApplyConfiguration) WithCustomResourcePolicy(value apiv1beta2.CustomResourcePolicy) *ModuleApplyConfiguration {
	b.CustomResourcePolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModuleApplyConfiguration) WithName(value string) *ModuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithControllerName sets the ControllerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerName field is set to the value of the last call.
func (b *ModuleApplyConfiguration) WithControllerName(value string) *ModuleApplyConfiguration {
	b.ControllerName = &value
	return b
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *ModuleApplyConfiguration) WithChannel(value string) *ModuleApplyConfiguration {
	b.Channel = &value
	return b
}

// WithRemoteModuleTemplateRef sets the RemoteModuleTemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteModuleTemplateRef field is set to the value of the last call.
func (b *ModuleApplyConfiguration) WithRemoteModuleTemplateRef(value string) *ModuleApplyConfiguration {
	b.RemoteModuleTemplateRef = &value
	return b
}

// WithManaged sets the Managed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Managed field is set to the value of the last call.
func (b *ModuleApplyConfiguration) WithManaged(value bool) *ModuleApplyConfiguration {
	b.Managed = &value
	return b
}
