// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ModuleReleaseMetaSpecApplyConfiguration represents a declarative configuration of the ModuleReleaseMetaSpec type for use
// with apply.
type ModuleReleaseMetaSpecApplyConfiguration struct {
	ModuleName       *string                                      `json:"moduleName,omitempty"`
	OcmComponentName *string                                      `json:"ocmComponentName,omitempty"`
	Channels         []ChannelVersionAssignmentApplyConfiguration `json:"channels,omitempty"`
	Mandatory        *MandatoryApplyConfiguration                 `json:"mandatory,omitempty"`
	Beta             *bool                                        `json:"beta,omitempty"`
	Internal         *bool                                        `json:"internal,omitempty"`
}

// ModuleReleaseMetaSpecApplyConfiguration constructs a declarative configuration of the ModuleReleaseMetaSpec type for use with
// apply.
func ModuleReleaseMetaSpec() *ModuleReleaseMetaSpecApplyConfiguration {
	return &ModuleReleaseMetaSpecApplyConfiguration{}
}

// WithModuleName sets the ModuleName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModuleName field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithModuleName(value string) *ModuleReleaseMetaSpecApplyConfiguration {
	b.ModuleName = &value
	return b
}

// WithOcmComponentName sets the OcmComponentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OcmComponentName field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithOcmComponentName(value string) *ModuleReleaseMetaSpecApplyConfiguration {
	b.OcmComponentName = &value
	return b
}

// WithChannels adds the given value to the Channels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Channels field.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithChannels(values ...*ChannelVersionAssignmentApplyConfiguration) *ModuleReleaseMetaSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithChannels")
		}
		b.Channels = append(b.Channels, *values[i])
	}
	return b
}

// WithMandatory sets the Mandatory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mandatory field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithMandatory(value *MandatoryApplyConfiguration) *ModuleReleaseMetaSpecApplyConfiguration {
	b.Mandatory = value
	return b
}

// WithBeta sets the Beta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Beta field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithBeta(value bool) *ModuleReleaseMetaSpecApplyConfiguration {
	b.Beta = &value
	return b
}

// WithInternal sets the Internal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Internal field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithInternal(value bool) *ModuleReleaseMetaSpecApplyConfiguration {
	b.Internal = &value
	return b
}
