// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ModuleIconApplyConfiguration represents a declarative configuration of the ModuleIcon type for use
// with apply.
type ModuleIconApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	Link *string `json:"link,omitempty"`
}

// ModuleIconApplyConfiguration constructs a declarative configuration of the ModuleIcon type for use with
// apply.
func ModuleIcon() *ModuleIconApplyConfiguration {
	return &ModuleIconApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModuleIconApplyConfiguration) WithName(value string) *ModuleIconApplyConfiguration {
	b.Name = &value
	return b
}

// WithLink sets the Link field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Link field is set to the value of the last call.
func (b *ModuleIconApplyConfiguration) WithLink(value string) *ModuleIconApplyConfiguration {
	b.Link = &value
	return b
}
