/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	shared "github.com/kyma-project/lifecycle-manager/api/shared"
)

// ModuleStatusApplyConfiguration represents a declarative configuration of the ModuleStatus type for use
// with apply.
type ModuleStatusApplyConfiguration struct {
	// Name defines the name of the Module in the Spec that the status is used for.
	// It can be any kind of Reference format supported by Module.Name.
	Name *string `json:"name,omitempty"`
	// Deprecated: This field is deprecated and will be removed in the upcoming API version.
	// Use the `OCMComponentName` field instead to track the OCM component name of the module.
	FQDN *string `json:"fqdn,omitempty"`
	// OCMComponentName represents the OCM (Open Component Model) component name of the module.
	OCMComponentName *string `json:"ocmComponentName,omitempty"`
	// Channel tracks the active Channel of the Module. In Case it changes, the new Channel will have caused
	// a new lookup to be necessary that maybe picks a different ModuleTemplate, which is why we need to reconcile.
	Channel *string `json:"channel,omitempty"`
	// Channel tracks the active Version of the Module.
	Version *string `json:"version,omitempty"`
	// Message is a human-readable message indicating details about the State.
	Message *string `json:"message,omitempty"`
	// State of the Module in the currently tracked Generation
	State *shared.State `json:"state,omitempty"`
	// Manifest contains the Information of a related Manifest
	Manifest *TrackingObjectApplyConfiguration `json:"manifest,omitempty"`
	// Resource contains information about the created module CR.
	Resource *TrackingObjectApplyConfiguration `json:"resource,omitempty"`
	// It contains information about the last parsed ModuleTemplate in Context of the Installation.
	// This will update when Channel or the ModuleTemplate is changed.
	Template *TrackingObjectApplyConfiguration `json:"template,omitempty"`
	// Maintenance indicates whether the module is currently in a maintenance window.
	Maintenance *bool `json:"maintenance,omitempty"`
}

// ModuleStatusApplyConfiguration constructs a declarative configuration of the ModuleStatus type for use with
// apply.
func ModuleStatus() *ModuleStatusApplyConfiguration {
	return &ModuleStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithName(value string) *ModuleStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithFQDN sets the FQDN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FQDN field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithFQDN(value string) *ModuleStatusApplyConfiguration {
	b.FQDN = &value
	return b
}

// WithOCMComponentName sets the OCMComponentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OCMComponentName field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithOCMComponentName(value string) *ModuleStatusApplyConfiguration {
	b.OCMComponentName = &value
	return b
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithChannel(value string) *ModuleStatusApplyConfiguration {
	b.Channel = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithVersion(value string) *ModuleStatusApplyConfiguration {
	b.Version = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithMessage(value string) *ModuleStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithState(value shared.State) *ModuleStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithManifest sets the Manifest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manifest field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithManifest(value *TrackingObjectApplyConfiguration) *ModuleStatusApplyConfiguration {
	b.Manifest = value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithResource(value *TrackingObjectApplyConfiguration) *ModuleStatusApplyConfiguration {
	b.Resource = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithTemplate(value *TrackingObjectApplyConfiguration) *ModuleStatusApplyConfiguration {
	b.Template = value
	return b
}

// WithMaintenance sets the Maintenance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maintenance field is set to the value of the last call.
func (b *ModuleStatusApplyConfiguration) WithMaintenance(value bool) *ModuleStatusApplyConfiguration {
	b.Maintenance = &value
	return b
}
