/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ModuleTemplateSpecApplyConfiguration represents a declarative configuration of the ModuleTemplateSpec type for use
// with apply.
//
// ModuleTemplateSpec defines the desired state of ModuleTemplate.
type ModuleTemplateSpecApplyConfiguration struct {
	// Channel is the targeted channel of the ModuleTemplate. It will be used to directly assign a Template
	// to a target channel. It has to be provided at any given time.
	//
	// Deprecated: This field is deprecated and will be removed in a future release.
	Channel *string `json:"channel,omitempty"`
	// Version identifies the version of the Module. Can be empty, or a semantic version.
	Version *string `json:"version,omitempty"`
	// ModuleName is the name of the Module. Can be empty.
	ModuleName *string `json:"moduleName,omitempty"`
	// Mandatory indicates whether the module is mandatory. It is used to enforce the installation of the module with
	// its configuration in all runtime clusters.
	Mandatory *bool `json:"mandatory,omitempty"`
	// Data is the default set of attributes that are used to generate the Module. It contains a default set of values
	// for a given channel, and is thus different from default values allocated during struct parsing of the Module.
	// While Data can change after the initial creation of ModuleTemplate, it is not expected to be propagated to
	// downstream modules as it is considered a set of default values. This means that an update of the data block
	// will only propagate to new Modules created form ModuleTemplate, not any existing Module.
	Data *unstructured.Unstructured `json:"data,omitempty"`
	// The Descriptor is the Open Component Model Descriptor of a Module, containing all relevant information
	// to correctly initialize a module (e.g. Manifests, References to Binaries and/or configuration)
	// Name more information on Component Descriptors, see
	// https://github.com/open-component-model/ocm
	//
	// It is translated inside the Lifecycle of the Cluster and will be used by downstream controllers
	// to bootstrap and manage the module. This part is also propagated for every change of the template.
	// This means for upgrades of the Descriptor, downstream controllers will also update the dependant modules
	// (e.g. by updating the controller binary linked in a chart referenced in the descriptor)
	//
	// NOTE: Only Raw Rendering is Supported for the layers. So previously used "config" layers for the helm
	// charts and kustomize renderers are deprecated and ignored.
	Descriptor *runtime.RawExtension `json:"descriptor,omitempty"`
	// CustomStateCheck is deprecated.
	CustomStateCheck []*apiv1beta2.CustomStateCheck `json:"customStateCheck,omitempty"`
	// Resources is a list of additional resources of the module that can be fetched, e.g., the raw manifest.
	Resources []ResourceApplyConfiguration `json:"resources,omitempty"`
	// Info contains metadata about the module.
	Info *ModuleInfoApplyConfiguration `json:"info,omitempty"`
	// AssociatedResources is a list of module related resources that usually must be cleaned when uninstalling a module. Informational purpose only.
	AssociatedResources []v1.GroupVersionKind `json:"associatedResources,omitempty"`
	// Manager contains information for identifying a module's resource that can be used as indicator for the installation readiness of the module. Typically, this is the manager Deployment of the module. In exceptional cases, it may also be another resource.
	Manager *ManagerApplyConfiguration `json:"manager,omitempty"`
	// RequiresDowntime indicates whether the module requires downtime in support of maintenance windows during module upgrades.
	RequiresDowntime *bool `json:"requiresDowntime,omitempty"`
}

// ModuleTemplateSpecApplyConfiguration constructs a declarative configuration of the ModuleTemplateSpec type for use with
// apply.
func ModuleTemplateSpec() *ModuleTemplateSpecApplyConfiguration {
	return &ModuleTemplateSpecApplyConfiguration{}
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithChannel(value string) *ModuleTemplateSpecApplyConfiguration {
	b.Channel = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithVersion(value string) *ModuleTemplateSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithModuleName sets the ModuleName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModuleName field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithModuleName(value string) *ModuleTemplateSpecApplyConfiguration {
	b.ModuleName = &value
	return b
}

// WithMandatory sets the Mandatory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mandatory field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithMandatory(value bool) *ModuleTemplateSpecApplyConfiguration {
	b.Mandatory = &value
	return b
}

// WithData sets the Data field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Data field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithData(value unstructured.Unstructured) *ModuleTemplateSpecApplyConfiguration {
	b.Data = &value
	return b
}

// WithDescriptor sets the Descriptor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Descriptor field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithDescriptor(value runtime.RawExtension) *ModuleTemplateSpecApplyConfiguration {
	b.Descriptor = &value
	return b
}

// WithCustomStateCheck adds the given value to the CustomStateCheck field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomStateCheck field.
func (b *ModuleTemplateSpecApplyConfiguration) WithCustomStateCheck(values ...**apiv1beta2.CustomStateCheck) *ModuleTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCustomStateCheck")
		}
		b.CustomStateCheck = append(b.CustomStateCheck, *values[i])
	}
	return b
}

// WithResources adds the given value to the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resources field.
func (b *ModuleTemplateSpecApplyConfiguration) WithResources(values ...*ResourceApplyConfiguration) *ModuleTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResources")
		}
		b.Resources = append(b.Resources, *values[i])
	}
	return b
}

// WithInfo sets the Info field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Info field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithInfo(value *ModuleInfoApplyConfiguration) *ModuleTemplateSpecApplyConfiguration {
	b.Info = value
	return b
}

// WithAssociatedResources adds the given value to the AssociatedResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AssociatedResources field.
func (b *ModuleTemplateSpecApplyConfiguration) WithAssociatedResources(values ...v1.GroupVersionKind) *ModuleTemplateSpecApplyConfiguration {
	for i := range values {
		b.AssociatedResources = append(b.AssociatedResources, values[i])
	}
	return b
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithManager(value *ManagerApplyConfiguration) *ModuleTemplateSpecApplyConfiguration {
	b.Manager = value
	return b
}

// WithRequiresDowntime sets the RequiresDowntime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiresDowntime field is set to the value of the last call.
func (b *ModuleTemplateSpecApplyConfiguration) WithRequiresDowntime(value bool) *ModuleTemplateSpecApplyConfiguration {
	b.RequiresDowntime = &value
	return b
}
