/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ModuleReleaseMetaSpecApplyConfiguration represents a declarative configuration of the ModuleReleaseMetaSpec type for use
// with apply.
//
// ModuleReleaseMetaSpec defines the channel-version assignments for a module.
type ModuleReleaseMetaSpecApplyConfiguration struct {
	// ModuleName is the name of the Module.
	ModuleName *string `json:"moduleName,omitempty"`
	// OcmComponentName is the name of the OCM component that this module belongs to.
	// https://github.com/open-component-model/ocm/blob/4473dacca406e4c84c0ac5e6e14393c659384afc/resources/component-descriptor-v2-schema.yaml#L40
	OcmComponentName *string `json:"ocmComponentName,omitempty"`
	// Channels is the list of module channels with their corresponding versions.
	Channels []ChannelVersionAssignmentApplyConfiguration `json:"channels,omitempty"`
	// Mandatory specifies a version for the mandatory module.
	Mandatory *MandatoryApplyConfiguration `json:"mandatory,omitempty"`
	// Beta indicates if the module is in beta state. Beta modules are only available for beta Kymas.
	//
	// Deprecated: This field is deprecated and will be removed in the upcoming API version.
	Beta *bool `json:"beta,omitempty"`
	// Internal indicates if the module is internal. Internal modules are only available for internal Kymas.
	//
	// Deprecated: This field is deprecated and will be removed in the upcoming API version.
	Internal *bool `json:"internal,omitempty"`
}

// ModuleReleaseMetaSpecApplyConfiguration constructs a declarative configuration of the ModuleReleaseMetaSpec type for use with
// apply.
func ModuleReleaseMetaSpec() *ModuleReleaseMetaSpecApplyConfiguration {
	return &ModuleReleaseMetaSpecApplyConfiguration{}
}

// WithModuleName sets the ModuleName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModuleName field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithModuleName(value string) *ModuleReleaseMetaSpecApplyConfiguration {
	b.ModuleName = &value
	return b
}

// WithOcmComponentName sets the OcmComponentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OcmComponentName field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithOcmComponentName(value string) *ModuleReleaseMetaSpecApplyConfiguration {
	b.OcmComponentName = &value
	return b
}

// WithChannels adds the given value to the Channels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Channels field.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithChannels(values ...*ChannelVersionAssignmentApplyConfiguration) *ModuleReleaseMetaSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithChannels")
		}
		b.Channels = append(b.Channels, *values[i])
	}
	return b
}

// WithMandatory sets the Mandatory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mandatory field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithMandatory(value *MandatoryApplyConfiguration) *ModuleReleaseMetaSpecApplyConfiguration {
	b.Mandatory = value
	return b
}

// WithBeta sets the Beta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Beta field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithBeta(value bool) *ModuleReleaseMetaSpecApplyConfiguration {
	b.Beta = &value
	return b
}

// WithInternal sets the Internal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Internal field is set to the value of the last call.
func (b *ModuleReleaseMetaSpecApplyConfiguration) WithInternal(value bool) *ModuleReleaseMetaSpecApplyConfiguration {
	b.Internal = &value
	return b
}
