// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ModuleInfoApplyConfiguration represents a declarative configuration of the ModuleInfo type for use
// with apply.
type ModuleInfoApplyConfiguration struct {
	Repository    *string                        `json:"repository,omitempty"`
	Documentation *string                        `json:"documentation,omitempty"`
	Icons         []ModuleIconApplyConfiguration `json:"icons,omitempty"`
}

// ModuleInfoApplyConfiguration constructs a declarative configuration of the ModuleInfo type for use with
// apply.
func ModuleInfo() *ModuleInfoApplyConfiguration {
	return &ModuleInfoApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *ModuleInfoApplyConfiguration) WithRepository(value string) *ModuleInfoApplyConfiguration {
	b.Repository = &value
	return b
}

// WithDocumentation sets the Documentation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Documentation field is set to the value of the last call.
func (b *ModuleInfoApplyConfiguration) WithDocumentation(value string) *ModuleInfoApplyConfiguration {
	b.Documentation = &value
	return b
}

// WithIcons adds the given value to the Icons field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Icons field.
func (b *ModuleInfoApplyConfiguration) WithIcons(values ...*ModuleIconApplyConfiguration) *ModuleInfoApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithIcons")
		}
		b.Icons = append(b.Icons, *values[i])
	}
	return b
}
