// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ResourceApplyConfiguration represents a declarative configuration of the Resource type for use
// with apply.
type ResourceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	Link *string `json:"link,omitempty"`
}

// ResourceApplyConfiguration constructs a declarative configuration of the Resource type for use with
// apply.
func Resource() *ResourceApplyConfiguration {
	return &ResourceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResourceApplyConfiguration) WithName(value string) *ResourceApplyConfiguration {
	b.Name = &value
	return b
}

// WithLink sets the Link field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Link field is set to the value of the last call.
func (b *ResourceApplyConfiguration) WithLink(value string) *ResourceApplyConfiguration {
	b.Link = &value
	return b
}
