/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TrackingObjectApplyConfiguration represents a declarative configuration of the TrackingObject type for use
// with apply.
//
// TrackingObject contains TypeMeta and PartialMeta to allow a generation based object tracking.
// It purposefully does not use ObjectMeta as the generation of controller-runtime for crds would not validate
// the generation fields even when embedding ObjectMeta.
type TrackingObjectApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	PartialMeta                   *PartialMetaApplyConfiguration `json:"metadata,omitempty"`
}

// TrackingObjectApplyConfiguration constructs a declarative configuration of the TrackingObject type for use with
// apply.
func TrackingObject() *TrackingObjectApplyConfiguration {
	b := &TrackingObjectApplyConfiguration{}
	b.WithKind("TrackingObject")
	b.WithAPIVersion("operator.kyma-project.io/v1beta2")
	return b
}

func (b TrackingObjectApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *TrackingObjectApplyConfiguration) WithKind(value string) *TrackingObjectApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *TrackingObjectApplyConfiguration) WithAPIVersion(value string) *TrackingObjectApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithPartialMeta sets the PartialMeta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartialMeta field is set to the value of the last call.
func (b *TrackingObjectApplyConfiguration) WithPartialMeta(value *PartialMetaApplyConfiguration) *TrackingObjectApplyConfiguration {
	b.PartialMeta = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *TrackingObjectApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *TrackingObjectApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}
