/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kyma-project/lifecycle-manager/api/v1beta2"
)

// WatcherSpecApplyConfiguration represents a declarative configuration of the WatcherSpec type for use
// with apply.
//
// WatcherSpec defines the desired state of Watcher.
type WatcherSpecApplyConfiguration struct {
	// ServiceInfo describes the service information of the listener
	ServiceInfo *ServiceApplyConfiguration `json:"serviceInfo,omitempty"`
	// Manager specifies the component responsible for handling webhook requests.
	Manager *string `json:"manager,omitempty"`
	// LabelsToWatch describes the labels that should be watched
	LabelsToWatch map[string]string `json:"labelsToWatch,omitempty"`
	// ResourceToWatch is the GroupVersionResource of the resource that should be watched.
	ResourceToWatch *WatchableGVRApplyConfiguration `json:"resourceToWatch,omitempty"`
	// Field describes the subresource that should be watched
	// Value can be one of ("spec", "status")
	Field *apiv1beta2.FieldName `json:"field,omitempty"`
	// Gateway configures the Istio Gateway for the VirtualService that is created/updated during processing
	// of the Watcher CR.
	Gateway *GatewayConfigApplyConfiguration `json:"gateway,omitempty"`
}

// WatcherSpecApplyConfiguration constructs a declarative configuration of the WatcherSpec type for use with
// apply.
func WatcherSpec() *WatcherSpecApplyConfiguration {
	return &WatcherSpecApplyConfiguration{}
}

// WithServiceInfo sets the ServiceInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceInfo field is set to the value of the last call.
func (b *WatcherSpecApplyConfiguration) WithServiceInfo(value *ServiceApplyConfiguration) *WatcherSpecApplyConfiguration {
	b.ServiceInfo = value
	return b
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *WatcherSpecApplyConfiguration) WithManager(value string) *WatcherSpecApplyConfiguration {
	b.Manager = &value
	return b
}

// WithLabelsToWatch puts the entries into the LabelsToWatch field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the LabelsToWatch field,
// overwriting an existing map entries in LabelsToWatch field with the same key.
func (b *WatcherSpecApplyConfiguration) WithLabelsToWatch(entries map[string]string) *WatcherSpecApplyConfiguration {
	if b.LabelsToWatch == nil && len(entries) > 0 {
		b.LabelsToWatch = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.LabelsToWatch[k] = v
	}
	return b
}

// WithResourceToWatch sets the ResourceToWatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceToWatch field is set to the value of the last call.
func (b *WatcherSpecApplyConfiguration) WithResourceToWatch(value *WatchableGVRApplyConfiguration) *WatcherSpecApplyConfiguration {
	b.ResourceToWatch = value
	return b
}

// WithField sets the Field field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Field field is set to the value of the last call.
func (b *WatcherSpecApplyConfiguration) WithField(value apiv1beta2.FieldName) *WatcherSpecApplyConfiguration {
	b.Field = &value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *WatcherSpecApplyConfiguration) WithGateway(value *GatewayConfigApplyConfiguration) *WatcherSpecApplyConfiguration {
	b.Gateway = value
	return b
}
