/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	shared "github.com/kyma-project/lifecycle-manager/api/shared"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// WatcherStatusApplyConfiguration represents a declarative configuration of the WatcherStatus type for use
// with apply.
//
// WatcherStatus defines the observed state of Watcher.
type WatcherStatusApplyConfiguration struct {
	// State signifies current state of a Watcher.
	// Value can be one of ("Ready", "Processing", "Error", "Deleting", "Warning")
	State *shared.State `json:"state,omitempty"`
	// List of status conditions to indicate the status of a Watcher.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// WatcherStatusApplyConfiguration constructs a declarative configuration of the WatcherStatus type for use with
// apply.
func WatcherStatus() *WatcherStatusApplyConfiguration {
	return &WatcherStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *WatcherStatusApplyConfiguration) WithState(value shared.State) *WatcherStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *WatcherStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *WatcherStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *WatcherStatusApplyConfiguration) WithObservedGeneration(value int64) *WatcherStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
