/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.kyma-project.lifecycle-manager.api.v1beta2.Kyma
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        map:
          elementType:
            scalar: untyped
            list:
              elementType:
                namedType: __untyped_atomic_
              elementRelationship: atomic
            map:
              elementType:
                namedType: __untyped_deduced_
              elementRelationship: separable
    - name: spec
      type:
        map:
          fields:
          - name: channel
            type:
              scalar: string
          - name: modules
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: channel
                      type:
                        scalar: string
                    - name: controller
                      type:
                        scalar: string
                    - name: customResourcePolicy
                      type:
                        scalar: string
                      default: CreateAndDelete
                    - name: managed
                      type:
                        scalar: boolean
                      default: true
                    - name: name
                      type:
                        scalar: string
                    - name: remoteModuleTemplateRef
                      type:
                        scalar: string
                elementRelationship: associative
                keys:
                - name
          - name: skipMaintenanceWindows
            type:
              scalar: boolean
    - name: status
      type:
        map:
          fields:
          - name: activeChannel
            type:
              scalar: string
          - name: conditions
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: lastTransitionTime
                      type:
                        scalar: untyped
                    - name: message
                      type:
                        scalar: string
                    - name: observedGeneration
                      type:
                        scalar: numeric
                    - name: reason
                      type:
                        scalar: string
                    - name: status
                      type:
                        scalar: string
                    - name: type
                      type:
                        scalar: string
                elementRelationship: associative
                keys:
                - type
          - name: lastOperation
            type:
              map:
                fields:
                - name: lastUpdateTime
                  type:
                    scalar: untyped
                - name: operation
                  type:
                    scalar: string
          - name: modules
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: channel
                      type:
                        scalar: string
                    - name: fqdn
                      type:
                        scalar: string
                    - name: maintenance
                      type:
                        scalar: boolean
                      default: false
                    - name: manifest
                      type:
                        map:
                          fields:
                          - name: apiVersion
                            type:
                              scalar: string
                          - name: kind
                            type:
                              scalar: string
                          - name: metadata
                            type:
                              map:
                                fields:
                                - name: generation
                                  type:
                                    scalar: numeric
                                - name: name
                                  type:
                                    scalar: string
                                - name: namespace
                                  type:
                                    scalar: string
                    - name: message
                      type:
                        scalar: string
                    - name: name
                      type:
                        scalar: string
                    - name: ocmComponentName
                      type:
                        scalar: string
                    - name: resource
                      type:
                        map:
                          fields:
                          - name: apiVersion
                            type:
                              scalar: string
                          - name: kind
                            type:
                              scalar: string
                          - name: metadata
                            type:
                              map:
                                fields:
                                - name: generation
                                  type:
                                    scalar: numeric
                                - name: name
                                  type:
                                    scalar: string
                                - name: namespace
                                  type:
                                    scalar: string
                    - name: state
                      type:
                        scalar: string
                    - name: template
                      type:
                        map:
                          fields:
                          - name: apiVersion
                            type:
                              scalar: string
                          - name: kind
                            type:
                              scalar: string
                          - name: metadata
                            type:
                              map:
                                fields:
                                - name: generation
                                  type:
                                    scalar: numeric
                                - name: name
                                  type:
                                    scalar: string
                                - name: namespace
                                  type:
                                    scalar: string
                    - name: version
                      type:
                        scalar: string
                elementRelationship: atomic
          - name: state
            type:
              scalar: string
- name: com.github.kyma-project.lifecycle-manager.api.v1beta2.Manifest
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        map:
          elementType:
            scalar: untyped
            list:
              elementType:
                namedType: __untyped_atomic_
              elementRelationship: atomic
            map:
              elementType:
                namedType: __untyped_deduced_
              elementRelationship: separable
    - name: spec
      type:
        map:
          fields:
          - name: config
            type:
              map:
                fields:
                - name: credSecretSelector
                  type:
                    map:
                      fields:
                      - name: matchExpressions
                        type:
                          list:
                            elementType:
                              map:
                                fields:
                                - name: key
                                  type:
                                    scalar: string
                                - name: operator
                                  type:
                                    scalar: string
                                - name: values
                                  type:
                                    list:
                                      elementType:
                                        scalar: string
                                      elementRelationship: atomic
                            elementRelationship: atomic
                      - name: matchLabels
                        type:
                          map:
                            elementType:
                              scalar: string
                      elementRelationship: atomic
                - name: name
                  type:
                    scalar: string
                - name: ref
                  type:
                    scalar: string
                - name: repo
                  type:
                    scalar: string
                - name: type
                  type:
                    scalar: string
          - name: customResourcePolicy
            type:
              scalar: string
            default: CreateAndDelete
          - name: install
            type:
              map:
                fields:
                - name: name
                  type:
                    scalar: string
                - name: source
                  type:
                    map:
                      elementType:
                        scalar: untyped
                        list:
                          elementType:
                            namedType: __untyped_atomic_
                          elementRelationship: atomic
                        map:
                          elementType:
                            namedType: __untyped_deduced_
                          elementRelationship: separable
          - name: localizedImages
            type:
              list:
                elementType:
                  scalar: string
                elementRelationship: atomic
          - name: manager
            type:
              map:
                fields:
                - name: group
                  type:
                    scalar: string
                - name: kind
                  type:
                    scalar: string
                - name: name
                  type:
                    scalar: string
                - name: namespace
                  type:
                    scalar: string
                - name: version
                  type:
                    scalar: string
          - name: remote
            type:
              scalar: boolean
          - name: resource
            type:
              map:
                elementType:
                  scalar: untyped
                  list:
                    elementType:
                      namedType: __untyped_atomic_
                    elementRelationship: atomic
                  map:
                    elementType:
                      namedType: __untyped_deduced_
                    elementRelationship: separable
          - name: version
            type:
              scalar: string
    - name: status
      type:
        map:
          fields:
          - name: conditions
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: lastTransitionTime
                      type:
                        scalar: untyped
                    - name: message
                      type:
                        scalar: string
                    - name: observedGeneration
                      type:
                        scalar: numeric
                    - name: reason
                      type:
                        scalar: string
                    - name: status
                      type:
                        scalar: string
                    - name: type
                      type:
                        scalar: string
                elementRelationship: associative
                keys:
                - type
          - name: lastOperation
            type:
              map:
                fields:
                - name: lastUpdateTime
                  type:
                    scalar: untyped
                - name: operation
                  type:
                    scalar: string
          - name: state
            type:
              scalar: string
          - name: synced
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: group
                      type:
                        scalar: string
                    - name: kind
                      type:
                        scalar: string
                    - name: name
                      type:
                        scalar: string
                    - name: namespace
                      type:
                        scalar: string
                    - name: version
                      type:
                        scalar: string
                elementRelationship: atomic
- name: com.github.kyma-project.lifecycle-manager.api.v1beta2.ModuleReleaseMeta
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        map:
          elementType:
            scalar: untyped
            list:
              elementType:
                namedType: __untyped_atomic_
              elementRelationship: atomic
            map:
              elementType:
                namedType: __untyped_deduced_
              elementRelationship: separable
    - name: spec
      type:
        map:
          fields:
          - name: beta
            type:
              scalar: boolean
            default: false
          - name: channels
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: channel
                      type:
                        scalar: string
                    - name: version
                      type:
                        scalar: string
                elementRelationship: associative
                keys:
                - channel
          - name: internal
            type:
              scalar: boolean
            default: false
          - name: mandatory
            type:
              map:
                fields:
                - name: version
                  type:
                    scalar: string
          - name: moduleName
            type:
              scalar: string
          - name: ocmComponentName
            type:
              scalar: string
- name: com.github.kyma-project.lifecycle-manager.api.v1beta2.ModuleTemplate
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        map:
          elementType:
            scalar: untyped
            list:
              elementType:
                namedType: __untyped_atomic_
              elementRelationship: atomic
            map:
              elementType:
                namedType: __untyped_deduced_
              elementRelationship: separable
    - name: spec
      type:
        map:
          fields:
          - name: associatedResources
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: group
                      type:
                        scalar: string
                    - name: kind
                      type:
                        scalar: string
                    - name: version
                      type:
                        scalar: string
                elementRelationship: atomic
          - name: channel
            type:
              scalar: string
          - name: customStateCheck
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: jsonPath
                      type:
                        scalar: string
                    - name: mappedState
                      type:
                        scalar: string
                    - name: value
                      type:
                        scalar: string
                elementRelationship: atomic
          - name: data
            type:
              map:
                elementType:
                  scalar: untyped
                  list:
                    elementType:
                      namedType: __untyped_atomic_
                    elementRelationship: atomic
                  map:
                    elementType:
                      namedType: __untyped_deduced_
                    elementRelationship: separable
          - name: descriptor
            type:
              map:
                elementType:
                  scalar: untyped
                  list:
                    elementType:
                      namedType: __untyped_atomic_
                    elementRelationship: atomic
                  map:
                    elementType:
                      namedType: __untyped_deduced_
                    elementRelationship: separable
          - name: info
            type:
              map:
                fields:
                - name: documentation
                  type:
                    scalar: string
                - name: icons
                  type:
                    list:
                      elementType:
                        map:
                          fields:
                          - name: link
                            type:
                              scalar: string
                          - name: name
                            type:
                              scalar: string
                      elementRelationship: associative
                      keys:
                      - name
                - name: repository
                  type:
                    scalar: string
          - name: manager
            type:
              map:
                fields:
                - name: group
                  type:
                    scalar: string
                - name: kind
                  type:
                    scalar: string
                - name: name
                  type:
                    scalar: string
                - name: namespace
                  type:
                    scalar: string
                - name: version
                  type:
                    scalar: string
          - name: mandatory
            type:
              scalar: boolean
          - name: moduleName
            type:
              scalar: string
          - name: requiresDowntime
            type:
              scalar: boolean
          - name: resources
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: link
                      type:
                        scalar: untyped
                    - name: name
                      type:
                        scalar: string
                elementRelationship: associative
                keys:
                - name
          - name: version
            type:
              scalar: string
- name: com.github.kyma-project.lifecycle-manager.api.v1beta2.Watcher
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        map:
          elementType:
            scalar: untyped
            list:
              elementType:
                namedType: __untyped_atomic_
              elementRelationship: atomic
            map:
              elementType:
                namedType: __untyped_deduced_
              elementRelationship: separable
    - name: spec
      type:
        map:
          fields:
          - name: field
            type:
              scalar: string
          - name: gateway
            type:
              map:
                fields:
                - name: selector
                  type:
                    map:
                      fields:
                      - name: matchExpressions
                        type:
                          list:
                            elementType:
                              map:
                                fields:
                                - name: key
                                  type:
                                    scalar: string
                                - name: operator
                                  type:
                                    scalar: string
                                - name: values
                                  type:
                                    list:
                                      elementType:
                                        scalar: string
                                      elementRelationship: atomic
                            elementRelationship: atomic
                      - name: matchLabels
                        type:
                          map:
                            elementType:
                              scalar: string
                      elementRelationship: atomic
          - name: labelsToWatch
            type:
              map:
                elementType:
                  scalar: string
          - name: manager
            type:
              scalar: string
          - name: resourceToWatch
            type:
              map:
                fields:
                - name: group
                  type:
                    scalar: string
                - name: resource
                  type:
                    scalar: string
                - name: version
                  type:
                    scalar: string
          - name: serviceInfo
            type:
              map:
                fields:
                - name: name
                  type:
                    scalar: string
                - name: namespace
                  type:
                    scalar: string
                - name: port
                  type:
                    scalar: numeric
    - name: status
      type:
        map:
          fields:
          - name: conditions
            type:
              list:
                elementType:
                  map:
                    fields:
                    - name: lastTransitionTime
                      type:
                        scalar: untyped
                    - name: message
                      type:
                        scalar: string
                    - name: observedGeneration
                      type:
                        scalar: numeric
                    - name: reason
                      type:
                        scalar: string
                    - name: status
                      type:
                        scalar: string
                    - name: type
                      type:
                        scalar: string
                elementRelationship: associative
                keys:
                - type
          - name: observedGeneration
            type:
              scalar: numeric
          - name: state
            type:
              scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
