name: Deploy lifecycle-manager E2E
description: Applies E2E test-specific patches to the lifecycle-manager kustomize and deploys it.
inputs:
  klm_version_tag:
    description: The version tag for the KLM image. For example, PR-123.
    required: true
  klm_image_repo:
    description: The repository for the KLM image. For example, dev.
    required: true
runs:
  using: composite
  steps:
    - uses: ./lifecycle-manager/.github/actions/switch-kubectl-context
      with:
        context_name: k3d-kcp
    - name: Set Kustomize Directory
      shell: bash
      run: |
        if [[ -n "${E2E_USE_GARDENER_CERT_MANAGER}" ]]; then
          echo "E2E_KUSTOMIZE_DIR=config/watcher_local_test_gcm" >> $GITHUB_ENV
        else
          echo "E2E_KUSTOMIZE_DIR=config/watcher_local_test" >> $GITHUB_ENV
        fi
    - name: Patch local OCI registry host
      if: ${{ matrix.e2e-test != 'oci-reg-cred-secret' && matrix.e2e-test != 'module-transferred-to-another-oci-registry' }}
      working-directory: lifecycle-manager
      shell: bash
      run: |
        pushd ${E2E_KUSTOMIZE_DIR}
        echo \
        "- op: add
          path: /spec/template/spec/containers/0/args/-
          value: --oci-registry-host=http://k3d-kcp-registry.localhost:5000" >> oci_registry_host.yaml
        cat oci_registry_host.yaml
        kustomize edit add patch --path oci_registry_host.yaml --kind Deployment
        popd
    - name: Patch remote OCI registry host
      if: ${{ matrix.e2e-test == 'module-transferred-to-another-oci-registry' }}
      working-directory: lifecycle-manager
      shell: bash
      run: |
        pushd ${E2E_KUSTOMIZE_DIR}
        echo \
        "- op: add
          path: /spec/template/spec/containers/0/args/-
          value: --oci-registry-host=https://europe-west3-docker.pkg.dev
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --modules-repository-subpath=sap-kyma-jellyfish-dev/restricted-market" >> oci_registry_host.yaml
        cat oci_registry_host.yaml
        kustomize edit add patch --path oci_registry_host.yaml --kind Deployment
        popd
    - name: Patch private OCI registry secret
      if: ${{ matrix.e2e-test == 'oci-reg-cred-secret' }}
      working-directory: lifecycle-manager
      shell: bash
      run: |
        pushd ${E2E_KUSTOMIZE_DIR}
        echo \
        "- op: add
          path: /spec/template/spec/containers/0/args/-
          value: --oci-registry-cred-secret=private-oci-reg-creds" >> oci_registry_host.yaml
        cat oci_registry_host.yaml
        kustomize edit add patch --path oci_registry_host.yaml --kind Deployment
        popd
    - name: Deploy LM local testing kustomize
      uses: ./lifecycle-manager/.github/actions/deploy-lifecycle-manager
      with:
        klm_version_tag: ${{ inputs.klm_version_tag }}
        klm_image_repo: ${{ inputs.klm_image_repo }}
    - name: Expose Metrics Endpoint
      working-directory: lifecycle-manager
      shell: bash
      run: |
        kubectl patch svc klm-controller-manager-metrics -p '{"spec": {"type": "LoadBalancer"}}' -n kcp-system
