name: Generate maintenance window policy file
description:
  Creates a maintenance window policy file in the JSON format.
  Overwrites the file if it already exists.
inputs:
  output_file_path:
    description: The path of the output file. For example, "lifecycle-manager/config/maintenance-windows/policy.json".
    required: true
runs:
  using: composite
  steps:
    - name: Generate policy file
      shell: bash
      run: |
        "${{ github.action_path }}/../../../scripts/tests/generate_maintenance_window_policy.sh" "${{ inputs.output_file_path }}"
