/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// ACMESpecApplyConfiguration represents a declarative configuration of the ACMESpec type for use
// with apply.
//
// ACMESpec is the ACME specific part of the spec.
type ACMESpecApplyConfiguration struct {
	// Server is the URL of the ACME server.
	Server *string `json:"server,omitempty"`
	// Email is the email address to use for user registration.
	Email *string `json:"email,omitempty"`
	// AutoRegistration is the flag if automatic registration should be applied if needed.
	AutoRegistration *bool `json:"autoRegistration,omitempty"`
	// PrivateKeySecretRef is the secret ref to the ACME private key.
	PrivateKeySecretRef *v1.SecretReferenceApplyConfiguration `json:"privateKeySecretRef,omitempty"`
	// ACMEExternalAccountBinding is a reference to a CA external account of the ACME server.
	ExternalAccountBinding *ACMEExternalAccountBindingApplyConfiguration `json:"externalAccountBinding,omitempty"`
	// SkipDNSChallengeValidation marks that this issuer does not validate DNS challenges.
	// In this case no DNS entries/records are created for a DNS Challenge and DNS propagation
	// is not checked.
	SkipDNSChallengeValidation *bool `json:"skipDNSChallengeValidation,omitempty"`
	// Domains optionally specifies domains allowed or forbidden for certificate requests
	Domains *DNSSelectionApplyConfiguration `json:"domains,omitempty"`
	// PrecheckNameservers overwrites the default precheck nameservers used for checking DNS propagation.
	// Format `host` or `host:port`, e.g. "8.8.8.8" same as "8.8.8.8:53" or "google-public-dns-a.google.com:53".
	PrecheckNameservers []string `json:"precheckNameservers,omitempty"`
}

// ACMESpecApplyConfiguration constructs a declarative configuration of the ACMESpec type for use with
// apply.
func ACMESpec() *ACMESpecApplyConfiguration {
	return &ACMESpecApplyConfiguration{}
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *ACMESpecApplyConfiguration) WithServer(value string) *ACMESpecApplyConfiguration {
	b.Server = &value
	return b
}

// WithEmail sets the Email field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Email field is set to the value of the last call.
func (b *ACMESpecApplyConfiguration) WithEmail(value string) *ACMESpecApplyConfiguration {
	b.Email = &value
	return b
}

// WithAutoRegistration sets the AutoRegistration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoRegistration field is set to the value of the last call.
func (b *ACMESpecApplyConfiguration) WithAutoRegistration(value bool) *ACMESpecApplyConfiguration {
	b.AutoRegistration = &value
	return b
}

// WithPrivateKeySecretRef sets the PrivateKeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeySecretRef field is set to the value of the last call.
func (b *ACMESpecApplyConfiguration) WithPrivateKeySecretRef(value *v1.SecretReferenceApplyConfiguration) *ACMESpecApplyConfiguration {
	b.PrivateKeySecretRef = value
	return b
}

// WithExternalAccountBinding sets the ExternalAccountBinding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalAccountBinding field is set to the value of the last call.
func (b *ACMESpecApplyConfiguration) WithExternalAccountBinding(value *ACMEExternalAccountBindingApplyConfiguration) *ACMESpecApplyConfiguration {
	b.ExternalAccountBinding = value
	return b
}

// WithSkipDNSChallengeValidation sets the SkipDNSChallengeValidation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipDNSChallengeValidation field is set to the value of the last call.
func (b *ACMESpecApplyConfiguration) WithSkipDNSChallengeValidation(value bool) *ACMESpecApplyConfiguration {
	b.SkipDNSChallengeValidation = &value
	return b
}

// WithDomains sets the Domains field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domains field is set to the value of the last call.
func (b *ACMESpecApplyConfiguration) WithDomains(value *DNSSelectionApplyConfiguration) *ACMESpecApplyConfiguration {
	b.Domains = value
	return b
}

// WithPrecheckNameservers adds the given value to the PrecheckNameservers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PrecheckNameservers field.
func (b *ACMESpecApplyConfiguration) WithPrecheckNameservers(values ...string) *ACMESpecApplyConfiguration {
	for i := range values {
		b.PrecheckNameservers = append(b.PrecheckNameservers, values[i])
	}
	return b
}
