/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackOffStateApplyConfiguration represents a declarative configuration of the BackOffState type for use
// with apply.
//
// BackOffState stores the status for exponential back off on repeated cert request failure
type BackOffStateApplyConfiguration struct {
	// ObservedGeneration is the observed generation the BackOffState is assigned to
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// RetryAfter is the timestamp this cert request is not retried before.
	RetryAfter *v1.Time `json:"recheckAfter,omitempty"`
	// RetryInterval is interval to wait for retrying.
	RetryInterval *v1.Duration `json:"recheckInterval,omitempty"`
}

// BackOffStateApplyConfiguration constructs a declarative configuration of the BackOffState type for use with
// apply.
func BackOffState() *BackOffStateApplyConfiguration {
	return &BackOffStateApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BackOffStateApplyConfiguration) WithObservedGeneration(value int64) *BackOffStateApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithRetryAfter sets the RetryAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryAfter field is set to the value of the last call.
func (b *BackOffStateApplyConfiguration) WithRetryAfter(value v1.Time) *BackOffStateApplyConfiguration {
	b.RetryAfter = &value
	return b
}

// WithRetryInterval sets the RetryInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryInterval field is set to the value of the last call.
func (b *BackOffStateApplyConfiguration) WithRetryInterval(value v1.Duration) *BackOffStateApplyConfiguration {
	b.RetryInterval = &value
	return b
}
