/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// CASpecApplyConfiguration represents a declarative configuration of the CASpec type for use
// with apply.
//
// CASpec is the CA specific part of the spec.
type CASpecApplyConfiguration struct {
	// PrivateKeySecretRef is the secret ref to the CA secret.
	PrivateKeySecretRef *v1.SecretReferenceApplyConfiguration `json:"privateKeySecretRef,omitempty"`
}

// CASpecApplyConfiguration constructs a declarative configuration of the CASpec type for use with
// apply.
func CASpec() *CASpecApplyConfiguration {
	return &CASpecApplyConfiguration{}
}

// WithPrivateKeySecretRef sets the PrivateKeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeySecretRef field is set to the value of the last call.
func (b *CASpecApplyConfiguration) WithPrivateKeySecretRef(value *v1.SecretReferenceApplyConfiguration) *CASpecApplyConfiguration {
	b.PrivateKeySecretRef = value
	return b
}
