/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CertificateRevocationStatusApplyConfiguration represents a declarative configuration of the CertificateRevocationStatus type for use
// with apply.
//
// CertificateRevocationStatus is the status of the certificate request.
type CertificateRevocationStatusApplyConfiguration struct {
	// ObservedGeneration is the observed generation of the spec.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// State is the certificate state.
	State *string `json:"state,omitempty"`
	// Message is the status or error message.
	Message *string `json:"message,omitempty"`
	// ObjectStatuses contains the statuses of the involved certificate objects
	Objects *ObjectStatusesApplyConfiguration `json:"objects,omitempty"`
	// SecretStatuses contains the statuses of the involved certificate secrets
	Secrets *SecretStatusesApplyConfiguration `json:"secrets,omitempty"`
	// RevocationApplied is the timestamp when the revocation was completed
	RevocationApplied *v1.Time `json:"revocationApplied,omitempty"`
}

// CertificateRevocationStatusApplyConfiguration constructs a declarative configuration of the CertificateRevocationStatus type for use with
// apply.
func CertificateRevocationStatus() *CertificateRevocationStatusApplyConfiguration {
	return &CertificateRevocationStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *CertificateRevocationStatusApplyConfiguration) WithObservedGeneration(value int64) *CertificateRevocationStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *CertificateRevocationStatusApplyConfiguration) WithState(value string) *CertificateRevocationStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *CertificateRevocationStatusApplyConfiguration) WithMessage(value string) *CertificateRevocationStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithObjects sets the Objects field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Objects field is set to the value of the last call.
func (b *CertificateRevocationStatusApplyConfiguration) WithObjects(value *ObjectStatusesApplyConfiguration) *CertificateRevocationStatusApplyConfiguration {
	b.Objects = value
	return b
}

// WithSecrets sets the Secrets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secrets field is set to the value of the last call.
func (b *CertificateRevocationStatusApplyConfiguration) WithSecrets(value *SecretStatusesApplyConfiguration) *CertificateRevocationStatusApplyConfiguration {
	b.Secrets = value
	return b
}

// WithRevocationApplied sets the RevocationApplied field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevocationApplied field is set to the value of the last call.
func (b *CertificateRevocationStatusApplyConfiguration) WithRevocationApplied(value v1.Time) *CertificateRevocationStatusApplyConfiguration {
	b.RevocationApplied = &value
	return b
}
