/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	certv1alpha1 "github.com/gardener/cert-management/pkg/apis/cert/v1alpha1"
)

// CertificatePrivateKeyApplyConfiguration represents a declarative configuration of the CertificatePrivateKey type for use
// with apply.
//
// CertificatePrivateKey contains configuration options for private keys
// used by the Certificate controller.
// These include the key algorithm and size.
type CertificatePrivateKeyApplyConfiguration struct {
	// Algorithm is the private key algorithm of the corresponding private key
	// for this certificate.
	//
	// If provided, allowed values are either `RSA` or `ECDSA`.
	// If `algorithm` is specified and `size` is not provided,
	// deployment specific default values will be used.
	Algorithm *certv1alpha1.PrivateKeyAlgorithm `json:"algorithm,omitempty"`
	// Size is the key bit size of the corresponding private key for this certificate.
	//
	// If `algorithm` is set to `RSA`, valid values are `2048`, `3072` or `4096`,
	// and will default to a deployment specific value if not specified.
	// If `algorithm` is set to `ECDSA`, valid values are `256` or `384`,
	// and will default to a deployment specific value if not specified.
	// No other values are allowed.
	Size *certv1alpha1.PrivateKeySize `json:"size,omitempty"`
	// The private key cryptography standards (PKCS) encoding for this
	// certificate's private key to be encoded in.
	//
	// If provided, allowed values are `PKCS1` and `PKCS8` standing for PKCS#1
	// and PKCS#8, respectively.
	// Defaults to `PKCS1` if not specified.
	Encoding *certv1alpha1.PrivateKeyEncoding `json:"encoding,omitempty"`
}

// CertificatePrivateKeyApplyConfiguration constructs a declarative configuration of the CertificatePrivateKey type for use with
// apply.
func CertificatePrivateKey() *CertificatePrivateKeyApplyConfiguration {
	return &CertificatePrivateKeyApplyConfiguration{}
}

// WithAlgorithm sets the Algorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Algorithm field is set to the value of the last call.
func (b *CertificatePrivateKeyApplyConfiguration) WithAlgorithm(value certv1alpha1.PrivateKeyAlgorithm) *CertificatePrivateKeyApplyConfiguration {
	b.Algorithm = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *CertificatePrivateKeyApplyConfiguration) WithSize(value certv1alpha1.PrivateKeySize) *CertificatePrivateKeyApplyConfiguration {
	b.Size = &value
	return b
}

// WithEncoding sets the Encoding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Encoding field is set to the value of the last call.
func (b *CertificatePrivateKeyApplyConfiguration) WithEncoding(value certv1alpha1.PrivateKeyEncoding) *CertificatePrivateKeyApplyConfiguration {
	b.Encoding = &value
	return b
}
