/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CertificateStatusApplyConfiguration represents a declarative configuration of the CertificateStatus type for use
// with apply.
//
// CertificateStatus is the status of the certificate request.
type CertificateStatusApplyConfiguration struct {
	// ObservedGeneration is the observed generation of the spec.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// State is the certificate state.
	State *string `json:"state,omitempty"`
	// Message is the status or error message.
	Message *string `json:"message,omitempty"`
	// LastPendingTimestamp contains the start timestamp of the last pending status.
	LastPendingTimestamp *v1.Time `json:"lastPendingTimestamp,omitempty"`
	// CommonName is the current CN.
	CommonName *string `json:"commonName,omitempty"`
	// DNSNames are the current domain names.
	DNSNames []string `json:"dnsNames,omitempty"`
	// IssuerRef is the used issuer.
	IssuerRef *QualifiedIssuerRefApplyConfiguration `json:"issuerRef,omitempty"`
	// IssuanceDate shows the notBefore validity date.
	IssuanceDate *string `json:"issuanceDate,omitempty"`
	// RenewalDate shows the planned renewal date. If not set, no renewal has been planned yet.
	RenewalDate *string `json:"renewalDate,omitempty"`
	// ExpirationDate shows the notAfter validity date.
	ExpirationDate *string `json:"expirationDate,omitempty"`
	// BackOff contains the state to back off failed certificate requests
	BackOff *BackOffStateApplyConfiguration `json:"backoff,omitempty"`
	// List of status conditions to indicate the status of certificates.
	// Known condition types are `Ready`.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// CertificateStatusApplyConfiguration constructs a declarative configuration of the CertificateStatus type for use with
// apply.
func CertificateStatus() *CertificateStatusApplyConfiguration {
	return &CertificateStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithObservedGeneration(value int64) *CertificateStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithState(value string) *CertificateStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithMessage(value string) *CertificateStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithLastPendingTimestamp sets the LastPendingTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastPendingTimestamp field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithLastPendingTimestamp(value v1.Time) *CertificateStatusApplyConfiguration {
	b.LastPendingTimestamp = &value
	return b
}

// WithCommonName sets the CommonName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonName field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithCommonName(value string) *CertificateStatusApplyConfiguration {
	b.CommonName = &value
	return b
}

// WithDNSNames adds the given value to the DNSNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DNSNames field.
func (b *CertificateStatusApplyConfiguration) WithDNSNames(values ...string) *CertificateStatusApplyConfiguration {
	for i := range values {
		b.DNSNames = append(b.DNSNames, values[i])
	}
	return b
}

// WithIssuerRef sets the IssuerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerRef field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithIssuerRef(value *QualifiedIssuerRefApplyConfiguration) *CertificateStatusApplyConfiguration {
	b.IssuerRef = value
	return b
}

// WithIssuanceDate sets the IssuanceDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuanceDate field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithIssuanceDate(value string) *CertificateStatusApplyConfiguration {
	b.IssuanceDate = &value
	return b
}

// WithRenewalDate sets the RenewalDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenewalDate field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithRenewalDate(value string) *CertificateStatusApplyConfiguration {
	b.RenewalDate = &value
	return b
}

// WithExpirationDate sets the ExpirationDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpirationDate field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithExpirationDate(value string) *CertificateStatusApplyConfiguration {
	b.ExpirationDate = &value
	return b
}

// WithBackOff sets the BackOff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackOff field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithBackOff(value *BackOffStateApplyConfiguration) *CertificateStatusApplyConfiguration {
	b.BackOff = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CertificateStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *CertificateStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
