/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// CertificateSpecApplyConfiguration represents a declarative configuration of the CertificateSpec type for use
// with apply.
//
// CertificateSpec is the spec of the certificate to request.
type CertificateSpecApplyConfiguration struct {
	// CommonName is the CN for the certificate (max. 64 chars).
	CommonName *string `json:"commonName,omitempty"`
	// DNSNames are the optional additional domain names of the certificate.
	DNSNames []string `json:"dnsNames,omitempty"`
	// EmailAddresses are the optional requested email subject alternative names.
	EmailAddresses []string `json:"emailAddresses,omitempty"`
	// IPAddresses are the optional requested IP address subject alternative names.
	IPAddresses []string `json:"ipAddresses,omitempty"`
	// URIs are the optional requested URI subject alternative names.
	URIs []string `json:"uris,omitempty"`
	// CSR is the alternative way to provide CN,DNSNames and other information.
	CSR []byte `json:"csr,omitempty"`
	// IssuerRef is the reference of the issuer to use.
	IssuerRef *IssuerRefApplyConfiguration `json:"issuerRef,omitempty"`
	// SecretName is the name of the secret object to use for storing the certificate.
	SecretName *string `json:"secretName,omitempty"`
	// SecretRef is the reference of the secret object to use for storing the certificate.
	SecretRef *v1.SecretReferenceApplyConfiguration `json:"secretRef,omitempty"`
	// SecretLabels are labels to add to the certificate secret.
	SecretLabels map[string]string `json:"secretLabels,omitempty"`
	// Renew triggers a renewal if set to true
	Renew *bool `json:"renew,omitempty"`
	// RenewBefore specifies the time before the certificate's expiration date when the certificate should be renewed.
	// Note that the actual expiration of the issued certificate is used for the calculation.
	// If not set, the default renewal window is used.
	// Must be at least 5 minutes and not greater than issued certificate's duration minus 5 minutes.
	// Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
	RenewBefore *metav1.Duration `json:"renewBefore,omitempty"`
	// EnsureRenewedAfter specifies a time stamp in the past. Renewing is only triggered if certificate notBefore date is before this date.
	EnsureRenewedAfter *metav1.Time `json:"ensureRenewedAfter,omitempty"`
	// FollowCNAME if true delegated domain for DNS01 challenge is used if CNAME record for DNS01 challenge domain `_acme-challenge.<domain>` is set.
	FollowCNAME *bool `json:"followCNAME,omitempty"`
	// Keystores configures additional keystore output formats stored in the `secretName`/`secretRef` Secret resource.
	Keystores *CertificateKeystoresApplyConfiguration `json:"keystores,omitempty"`
	// PreferredChain allows to specify the preferred certificate chain: if the CA offers multiple certificate chains, prefer the chain with an issuer matching this Subject Common Name. If no match, the default offered chain will be used.
	PreferredChain *string `json:"preferredChain,omitempty"`
	// Private key options. These include the key algorithm and size.
	PrivateKey *CertificatePrivateKeyApplyConfiguration `json:"privateKey,omitempty"`
	// IsCA value is used to set the `isCA` field on the certificate request.
	// Note that the issuer may choose to ignore the requested isCA value, just
	// like any other requested attribute.
	IsCA *bool `json:"isCA,omitempty"`
	// Requested 'duration' (i.e. lifetime) of the Certificate. Note that the
	// ACME issuer may choose to ignore the requested duration, just like any other
	// requested attribute.
	// If unset, this defaults to 90 days (2160h).
	// Must be at least twice the renewal window.
	// Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
	Duration *metav1.Duration `json:"duration,omitempty"`
}

// CertificateSpecApplyConfiguration constructs a declarative configuration of the CertificateSpec type for use with
// apply.
func CertificateSpec() *CertificateSpecApplyConfiguration {
	return &CertificateSpecApplyConfiguration{}
}

// WithCommonName sets the CommonName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonName field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithCommonName(value string) *CertificateSpecApplyConfiguration {
	b.CommonName = &value
	return b
}

// WithDNSNames adds the given value to the DNSNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DNSNames field.
func (b *CertificateSpecApplyConfiguration) WithDNSNames(values ...string) *CertificateSpecApplyConfiguration {
	for i := range values {
		b.DNSNames = append(b.DNSNames, values[i])
	}
	return b
}

// WithEmailAddresses adds the given value to the EmailAddresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EmailAddresses field.
func (b *CertificateSpecApplyConfiguration) WithEmailAddresses(values ...string) *CertificateSpecApplyConfiguration {
	for i := range values {
		b.EmailAddresses = append(b.EmailAddresses, values[i])
	}
	return b
}

// WithIPAddresses adds the given value to the IPAddresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPAddresses field.
func (b *CertificateSpecApplyConfiguration) WithIPAddresses(values ...string) *CertificateSpecApplyConfiguration {
	for i := range values {
		b.IPAddresses = append(b.IPAddresses, values[i])
	}
	return b
}

// WithURIs adds the given value to the URIs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the URIs field.
func (b *CertificateSpecApplyConfiguration) WithURIs(values ...string) *CertificateSpecApplyConfiguration {
	for i := range values {
		b.URIs = append(b.URIs, values[i])
	}
	return b
}

// WithCSR adds the given value to the CSR field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CSR field.
func (b *CertificateSpecApplyConfiguration) WithCSR(values ...byte) *CertificateSpecApplyConfiguration {
	for i := range values {
		b.CSR = append(b.CSR, values[i])
	}
	return b
}

// WithIssuerRef sets the IssuerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerRef field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithIssuerRef(value *IssuerRefApplyConfiguration) *CertificateSpecApplyConfiguration {
	b.IssuerRef = value
	return b
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithSecretName(value string) *CertificateSpecApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithSecretRef(value *v1.SecretReferenceApplyConfiguration) *CertificateSpecApplyConfiguration {
	b.SecretRef = value
	return b
}

// WithSecretLabels puts the entries into the SecretLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SecretLabels field,
// overwriting an existing map entries in SecretLabels field with the same key.
func (b *CertificateSpecApplyConfiguration) WithSecretLabels(entries map[string]string) *CertificateSpecApplyConfiguration {
	if b.SecretLabels == nil && len(entries) > 0 {
		b.SecretLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SecretLabels[k] = v
	}
	return b
}

// WithRenew sets the Renew field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Renew field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithRenew(value bool) *CertificateSpecApplyConfiguration {
	b.Renew = &value
	return b
}

// WithRenewBefore sets the RenewBefore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenewBefore field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithRenewBefore(value metav1.Duration) *CertificateSpecApplyConfiguration {
	b.RenewBefore = &value
	return b
}

// WithEnsureRenewedAfter sets the EnsureRenewedAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnsureRenewedAfter field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithEnsureRenewedAfter(value metav1.Time) *CertificateSpecApplyConfiguration {
	b.EnsureRenewedAfter = &value
	return b
}

// WithFollowCNAME sets the FollowCNAME field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FollowCNAME field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithFollowCNAME(value bool) *CertificateSpecApplyConfiguration {
	b.FollowCNAME = &value
	return b
}

// WithKeystores sets the Keystores field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Keystores field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithKeystores(value *CertificateKeystoresApplyConfiguration) *CertificateSpecApplyConfiguration {
	b.Keystores = value
	return b
}

// WithPreferredChain sets the PreferredChain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreferredChain field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithPreferredChain(value string) *CertificateSpecApplyConfiguration {
	b.PreferredChain = &value
	return b
}

// WithPrivateKey sets the PrivateKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKey field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithPrivateKey(value *CertificatePrivateKeyApplyConfiguration) *CertificateSpecApplyConfiguration {
	b.PrivateKey = value
	return b
}

// WithIsCA sets the IsCA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsCA field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithIsCA(value bool) *CertificateSpecApplyConfiguration {
	b.IsCA = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *CertificateSpecApplyConfiguration) WithDuration(value metav1.Duration) *CertificateSpecApplyConfiguration {
	b.Duration = &value
	return b
}
