/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CertificateRevocationSpecApplyConfiguration represents a declarative configuration of the CertificateRevocationSpec type for use
// with apply.
//
// CertificateRevocationSpec is the spec of the certificate revocation.
type CertificateRevocationSpecApplyConfiguration struct {
	// CertificateRef is the references to the certificate to be revoked
	CertificateRef *CertificateRefApplyConfiguration `json:"certificateRef,omitempty"`
	// Renew specifies if certificate objects should be renewed before revoking old certificates
	Renew *bool `json:"renew,omitempty"`
	// QualifyingDate specifies that any certificate with the same DNS names like the given 'certificateRef' should be revoked
	// if it is valid before this date. If not specified, it will be filled with the current time.
	QualifyingDate *v1.Time `json:"qualifyingDate,omitempty"`
}

// CertificateRevocationSpecApplyConfiguration constructs a declarative configuration of the CertificateRevocationSpec type for use with
// apply.
func CertificateRevocationSpec() *CertificateRevocationSpecApplyConfiguration {
	return &CertificateRevocationSpecApplyConfiguration{}
}

// WithCertificateRef sets the CertificateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateRef field is set to the value of the last call.
func (b *CertificateRevocationSpecApplyConfiguration) WithCertificateRef(value *CertificateRefApplyConfiguration) *CertificateRevocationSpecApplyConfiguration {
	b.CertificateRef = value
	return b
}

// WithRenew sets the Renew field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Renew field is set to the value of the last call.
func (b *CertificateRevocationSpecApplyConfiguration) WithRenew(value bool) *CertificateRevocationSpecApplyConfiguration {
	b.Renew = &value
	return b
}

// WithQualifyingDate sets the QualifyingDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QualifyingDate field is set to the value of the last call.
func (b *CertificateRevocationSpecApplyConfiguration) WithQualifyingDate(value v1.Time) *CertificateRevocationSpecApplyConfiguration {
	b.QualifyingDate = &value
	return b
}
