/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// QualifiedIssuerRefApplyConfiguration represents a declarative configuration of the QualifiedIssuerRef type for use
// with apply.
//
// QualifiedIssuerRef is the full qualified issuer reference.
type QualifiedIssuerRefApplyConfiguration struct {
	// Cluster is the cluster name of the issuer ('default' or 'target').
	// optional because of backwards compatibility
	Cluster *string `json:"cluster,omitempty"`
	// Name is the name of the issuer.
	Name *string `json:"name,omitempty"`
	// Namespace is the namespace of the issuer.
	Namespace *string `json:"namespace,omitempty"`
}

// QualifiedIssuerRefApplyConfiguration constructs a declarative configuration of the QualifiedIssuerRef type for use with
// apply.
func QualifiedIssuerRef() *QualifiedIssuerRefApplyConfiguration {
	return &QualifiedIssuerRefApplyConfiguration{}
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *QualifiedIssuerRefApplyConfiguration) WithCluster(value string) *QualifiedIssuerRefApplyConfiguration {
	b.Cluster = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *QualifiedIssuerRefApplyConfiguration) WithName(value string) *QualifiedIssuerRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *QualifiedIssuerRefApplyConfiguration) WithNamespace(value string) *QualifiedIssuerRefApplyConfiguration {
	b.Namespace = &value
	return b
}
