/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SecretStatusesApplyConfiguration represents a declarative configuration of the SecretStatuses type for use
// with apply.
//
// SecretStatuses contains the statuses of the involved certificate secrets
type SecretStatusesApplyConfiguration struct {
	// Processing is the list of certificate secrets to be processed
	Processing []CertificateSecretRefApplyConfiguration `json:"processing,omitempty"`
	// Revoked is the list of certificate secrets successfully revoked
	Revoked []CertificateSecretRefApplyConfiguration `json:"revoked,omitempty"`
	// Failed is the list of certificate secrets whose revocation failed
	Failed []CertificateSecretRefApplyConfiguration `json:"failed,omitempty"`
}

// SecretStatusesApplyConfiguration constructs a declarative configuration of the SecretStatuses type for use with
// apply.
func SecretStatuses() *SecretStatusesApplyConfiguration {
	return &SecretStatusesApplyConfiguration{}
}

// WithProcessing adds the given value to the Processing field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Processing field.
func (b *SecretStatusesApplyConfiguration) WithProcessing(values ...*CertificateSecretRefApplyConfiguration) *SecretStatusesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProcessing")
		}
		b.Processing = append(b.Processing, *values[i])
	}
	return b
}

// WithRevoked adds the given value to the Revoked field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Revoked field.
func (b *SecretStatusesApplyConfiguration) WithRevoked(values ...*CertificateSecretRefApplyConfiguration) *SecretStatusesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRevoked")
		}
		b.Revoked = append(b.Revoked, *values[i])
	}
	return b
}

// WithFailed adds the given value to the Failed field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Failed field.
func (b *SecretStatusesApplyConfiguration) WithFailed(values ...*CertificateSecretRefApplyConfiguration) *SecretStatusesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFailed")
		}
		b.Failed = append(b.Failed, *values[i])
	}
	return b
}
