name: Lint golangci

on:
  pull_request:
    branches:
      - main
      - feat/**
  workflow_dispatch:

permissions: { }

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: lifecycle-manager
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: './lifecycle-manager/go.mod'
          cache: false
      - name: Get configuration
        uses: ./lifecycle-manager/.github/actions/get-configuration
        id: configuration
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager
          skip-cache: true
          install-mode: binary
        env:
          GOSUMDB: sum.golang.org
      - name: golangci-lint for api module
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager/api
          skip-cache: true
          install-mode: binary
        env:
          GOSUMDB: sum.golang.org
      - name: golangci-lint for maintenancewindows module
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager/maintenancewindows
          skip-cache: true
          install-mode: binary
        env:
          GOSUMDB: sum.golang.org
