name: Lint golangci

on:
  pull_request:
    branches:
      - main
      - feat/**
  workflow_dispatch:

permissions: { }

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: lifecycle-manager
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: './lifecycle-manager/go.mod'
          cache: false
      - name: Get configuration
        uses: ./lifecycle-manager/.github/actions/get-configuration
        id: configuration
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager
          skip-cache: true
          install-mode: binary
        env:
          GOSUMDB: sum.golang.org
      - name: golangci-lint for api module
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager/api
          skip-cache: true
          install-mode: binary
        env:
          GOSUMDB: sum.golang.org
      - name: golangci-lint for maintenancewindows module
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager/maintenancewindows
          skip-cache: true
          install-mode: binary
        env:
          GOSUMDB: sum.golang.org
