name: Lint yaml

permissions: { }

on:
  pull_request:
    branches:
      - main
      - feat/**
  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: lifecycle-manager
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@b74a2626a991d676b6ec243a6458ff86cccf2d2d
        with:
          no_warnings: true
          config_file: ./lifecycle-manager/.yamllint.yml
