name: Lint Markdown Links
run-name: ${{github.event.pull_request.title}}

permissions: { }

on:
  pull_request:
  schedule:
    # Run every day at 5:00 AM
    - cron: "0 5 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # v1.0.17
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
          check-modified-files-only: 'no'
          base-branch: 'main'
