name: TestSuite E2E

permissions: { }

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: "With Kubernetes version (format: X.Y.Z)"
        required: false
      template_operator_version:
        description: "Template operator version (tag or branch)"
        required: false
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  wait-for-image-build:
    name: Wait for image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Set Image
        run: |
          if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
            echo "IMAGE=europe-docker.pkg.dev/kyma-project/dev/lifecycle-manager:${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            # Manually executed workflow should use the latest image of main branch
            echo "IMAGE=europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:latest" >> $GITHUB_ENV
          fi
      - name: Wait for the Docker image
        timeout-minutes: 20
        env:
          ITERATIONS: 40
          SLEEP_SECONDS: 30
        run: ./.github/scripts/release/wait_for_image.sh ${{ env.IMAGE }} ${{ env.ITERATIONS }} ${{ env.SLEEP_SECONDS}}
  e2e-integration:
    name: E2E
    needs: wait-for-image-build
    strategy:
      fail-fast: false
      matrix:
        e2e-test:
          - watcher-enqueue
          - kyma-deprovision-with-foreground-propagation
          - kyma-deprovision-with-background-propagation
          - module-status-decoupling-with-statefulset
          - module-status-decoupling-with-deployment
          - kyma-metrics
          - fips-mode-metric
          - module-without-default-cr
          - module-consistency
          - non-blocking-deletion
          - module-deletion-with-only-default-cr
          - modulereleasemeta-upgrade-under-deletion
          - module-api-upgrade-under-blocked-deletion
          - purge-controller
          - purge-metrics
          - module-upgrade-channel-switch
          - modulereleasemeta-module-upgrade-new-version
          - unmanage-module
          - skip-manifest-reconciliation
          - self-signed-certificate-rotation
          - mandatory-module
          - mandatory-module-metrics
          - misconfigured-kyma-secret
          - rbac-privileges
          - modulereleasemeta-sync
          - module-status-on-skr-connection-lost
          - modulereleasemeta-watch-trigger
          - modulereleasemeta-not-allowed-installation
          - labelling
          - maintenance-windows
          - maintenance-windows-initial-installation
          - maintenance-windows-skip
          - watcher-zero-downtime
          - module-deletion-blocking-with-multiple-crs-ignore-policy
          - module-deletion-blocking-with-multiple-crs-create-and-delete-policy
          - module-deletion-blocking-with-default-cr-with-finalizer
          - module-deletion-blocking-with-cross-namespace-ignore-policy
          - module-deletion-blocking-with-cross-namespace-create-and-delete-policy
          - module-deletion-blocking-with-cluster-scoped-crs-ignore-policy
          - module-deletion-blocking-with-cluster-scoped-crs-create-and-delete-policy
          - oci-reg-cred-secret
          - module-transferred-to-another-oci-registry
          - simulate-skr-secret-rotation-evict-client-cache
          - skr-image-pull-secret-sync
          - gateway-secret-server-cert-metric
          - restricted-module-catalog-sync
          - restricted-modules
          - deployer-module-image-pull-secret-injection
          - block-non-deployer-module-image-pull-secret-injection

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: lifecycle-manager
      - name: Checkout template-operator
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: kyma-project/template-operator
          path: template-operator
          ref: ${{ inputs.template_operator_version || steps.configuration.outputs.template_operator_version }}

      - name: Get configuration
        uses: ./lifecycle-manager/.github/actions/get-configuration
        id: configuration
      - name: Setup tools
        uses: ./lifecycle-manager/.github/actions/setup-tools
        with:
          k8s_version: ${{ steps.configuration.outputs.k8s_version }}
          istio_version: ${{ steps.configuration.outputs.istio_version }}
          k3d_version: ${{ steps.configuration.outputs.k3d_version }}
          ocm_cli_version: ${{ steps.configuration.outputs.ocm_cli_version }}
          modulectl_version: ${{ steps.configuration.outputs.modulectl_version }}
          go-version-file: lifecycle-manager/go.mod
          cache-dependency-path: lifecycle-manager/go.sum
      - name: Check if test manages its own setup
        id: setup-check
        run: |
          case "${{ matrix.e2e-test }}" in
            mandatory-module | \
            mandatory-module-metrics | \
            gateway-secret-server-cert-metric | \
            restricted-modules | \
            restricted-module-catalog-sync | \
            deployer-module-image-pull-secret-injection | \
            block-non-deployer-module-image-pull-secret-injection | \
            kyma-deprovision-with-foreground-propagation | \
            kyma-deprovision-with-background-propagation | \
            kyma-metrics | \
            module-consistency | \
            module-deletion-with-only-default-cr | \
            unmanage-module | \
            skip-manifest-reconciliation | \
            misconfigured-kyma-secret | \
            module-deletion-blocking-with-multiple-crs-ignore-policy | \
            module-deletion-blocking-with-multiple-crs-create-and-delete-policy | \
            module-deletion-blocking-with-default-cr-with-finalizer | \
            module-deletion-blocking-with-cross-namespace-ignore-policy | \
            module-deletion-blocking-with-cross-namespace-create-and-delete-policy | \
            module-deletion-blocking-with-cluster-scoped-crs-ignore-policy | \
            module-deletion-blocking-with-cluster-scoped-crs-create-and-delete-policy | \
            module-status-decoupling-with-statefulset | \
            module-status-decoupling-with-deployment | \
            module-without-default-cr | \
            purge-controller | \
            purge-metrics | \
            self-signed-certificate-rotation | \
            skr-image-pull-secret-sync | \
            watcher-enqueue | \
            rbac-privileges | \
            labelling | \
            fips-mode-metric | \
            watcher-zero-downtime | \
            modulereleasemeta-watch-trigger | \
            module-upgrade-channel-switch | \
            modulereleasemeta-module-upgrade-new-version | \
            modulereleasemeta-upgrade-under-deletion | \
            modulereleasemeta-sync | \
            module-status-on-skr-connection-lost | \
            modulereleasemeta-not-allowed-installation | \
            simulate-skr-secret-rotation-evict-client-cache | \
            non-blocking-deletion | \
            maintenance-windows | \
            maintenance-windows-initial-installation | \
            maintenance-windows-skip | \
            oci-reg-cred-secret | \
            module-transferred-to-another-oci-registry | \
            module-api-upgrade-under-blocked-deletion)
              echo "self-contained=true" >> $GITHUB_OUTPUT ;;
            *)
              echo "self-contained=false" >> $GITHUB_OUTPUT ;;
          esac

      - name: Setup test clusters
        if: ${{ steps.setup-check.outputs.self-contained == 'false' }}
        uses: ./lifecycle-manager/.github/actions/setup-test-clusters
        with:
          k8s_version: ${{ steps.configuration.outputs.k8s_version }}
          cert_manager_version: ${{ steps.configuration.outputs.cert_manager_version }}

      - name: Deploy lifecycle-manager
        if: ${{ steps.setup-check.outputs.self-contained == 'false' }}
        uses: ./lifecycle-manager/.github/actions/deploy-lifecycle-manager-e2e
        with:
          klm_version_tag: ${{ steps.configuration.outputs.klm_version_tag }}
          klm_image_repo: ${{ steps.configuration.outputs.klm_image_repo }}
      - name: Read e2e module versions
        id: e2e-versions
        working-directory: lifecycle-manager
        shell: bash
        run: |
          BASE_OLDER=$(yq -e '.["module-version-older"]' versions.yaml)
          BASE_NEWER=$(yq -e '.["module-version-newer"]' versions.yaml)
          BASE_OLDER_MAJOR=$(echo "$BASE_OLDER" | cut -d. -f1)
          BASE_NEWER_MAJOR=$(echo "$BASE_NEWER" | cut -d. -f1)
          echo "older=${BASE_OLDER}" >> "$GITHUB_OUTPUT"
          echo "newer=${BASE_NEWER}" >> "$GITHUB_OUTPUT"
          echo "older_major=${BASE_OLDER_MAJOR}" >> "$GITHUB_OUTPUT"
          echo "newer_major=${BASE_NEWER_MAJOR}" >> "$GITHUB_OUTPUT"
      - name: Deploy template-operator
        if: ${{ steps.setup-check.outputs.self-contained == 'false' }}
        uses: ./lifecycle-manager/.github/actions/deploy-template-operator-with-modulereleasemeta
        with:
          module_version: ${{ steps.configuration.outputs.template_operator_version }}
        env:
          ModuleDeploymentName: template-operator-controller-manager
          ModuleDeploymentNameInNewerVersion: template-operator-v${{ steps.e2e-versions.outputs.newer_major }}-controller-manager
          ModuleDeploymentNameInOlderVersion: template-operator-v${{ steps.e2e-versions.outputs.older_major }}-controller-manager
          NewerVersion: ${{ steps.e2e-versions.outputs.newer }}-e2e
          OlderVersion: ${{ steps.e2e-versions.outputs.older }}-e2e
          VersionForStatefulSetInWarning: ${{ steps.e2e-versions.outputs.older }}-warning-statefulset
          VersionForDeploymentInWarning: ${{ steps.e2e-versions.outputs.older }}-warning-deployment
          VersionForMisconfiguredDeploymentImage: ${{ steps.e2e-versions.outputs.older }}-misconfigured-deployment
          VersionForMisconfiguredStatefulSetImage: ${{ steps.e2e-versions.outputs.older }}-misconfigured-statefulset
          VersionForNoDefaultCR: ${{ steps.e2e-versions.outputs.older }}-no-default-cr
          MisconfiguredModuleName: template-operator-misconfigured
          ModuleName: template-operator
      - name: Run '${{ matrix.e2e-test }}' test
        working-directory: lifecycle-manager
        env:
          MODULE_VERSION: ${{ steps.configuration.outputs.template_operator_version }}
          KLM_VERSION_TAG: ${{ steps.configuration.outputs.klm_version_tag }}
          KLM_IMAGE_REPO: ${{ steps.configuration.outputs.klm_image_repo }}
        run: |
          make -C tests/e2e ${{ matrix.e2e-test }}
      - name: Post debug
        if: always()
        run: ./lifecycle-manager/.github/scripts/debug/teardown.sh
        continue-on-error: true
