name: TestSuite E2E with Gardener CertManager

permissions: { }

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: "With Kubernetes version (format: X.Y.Z)"
        required: false
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  wait-for-image-build:
    name: Wait for image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Set Image
        run: |
          if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
            echo "IMAGE=europe-docker.pkg.dev/kyma-project/dev/lifecycle-manager:${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            # Manually executed workflow should use the latest image of main branch
            echo "IMAGE=europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:latest" >> $GITHUB_ENV
          fi
      - name: Wait for the Docker image
        timeout-minutes: 20
        env:
          ITERATIONS: 40
          SLEEP_SECONDS: 30
        run: ./.github/scripts/release/wait_for_image.sh ${{ env.IMAGE }} ${{ env.ITERATIONS }} ${{ env.SLEEP_SECONDS}}
  e2e-tests:
    name: E2E With Gardener CertManager
    needs: wait-for-image-build
    strategy:
      fail-fast: false
      matrix:
        e2e-test:
          - watcher-enqueue
          - watcher-zero-downtime

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: lifecycle-manager
      - name: Get configuration
        uses: ./lifecycle-manager/.github/actions/get-configuration
        id: configuration
      - name: Checkout template-operator
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: kyma-project/template-operator
          path: template-operator
          ref: ${{ steps.configuration.outputs.template_operator_version }}
      - name: Setup tools
        uses: ./lifecycle-manager/.github/actions/setup-tools
        with:
          k8s_version: ${{ steps.configuration.outputs.k8s_version }}
          istio_version: ${{ steps.configuration.outputs.istio_version }}
          k3d_version: ${{ steps.configuration.outputs.k3d_version }}
          ocm_cli_version: ${{ steps.configuration.outputs.ocm_cli_version }}
          modulectl_version: ${{ steps.configuration.outputs.modulectl_version }}
          go-version-file: lifecycle-manager/go.mod
          cache-dependency-path: lifecycle-manager/go.sum
      - name: Run '${{ matrix.e2e-test }}' test
        working-directory: lifecycle-manager
        env:
          KLM_VERSION_TAG: ${{ steps.configuration.outputs.klm_version_tag }}
          KLM_IMAGE_REPO: ${{ steps.configuration.outputs.klm_image_repo }}
        run: |
          if [[ "${{ matrix.e2e-test }}" == "watcher-enqueue" ]]; then
            make -f tests/e2e/watcher_enqueue_gcm_test.mk test
          elif [[ "${{ matrix.e2e-test }}" == "watcher-zero-downtime" ]]; then
            make -f tests/e2e/watcher_zero_downtime_gcm_test.mk test
          fi
      - name: Post debug
        if: always()
        run: ./lifecycle-manager/.github/scripts/debug/teardown.sh
        continue-on-error: true
