name: TestSuite integration (local - single spec)

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  envtest-single-spec:
    name: "Run single integration spec"
    runs-on: ubuntu-latest
    env:
      GOSUMDB: sum.golang.org
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: lifecycle-manager
      - name: Get configuration
        uses: ./lifecycle-manager/.github/actions/get-configuration
        id: configuration
      - name: Setup tools
        uses: ./lifecycle-manager/.github/actions/setup-tools
        with:
          k8s_version: ${{ steps.configuration.outputs.k8s_version }}
          istio_version: ${{ steps.configuration.outputs.istio_version }}
          k3d_version: ${{ steps.configuration.outputs.k3d_version }}
          ocm_cli_version: ${{ steps.configuration.outputs.ocm_cli_version }}
          modulectl_version: ${{ steps.configuration.outputs.modulectl_version }}
          go-version-file: lifecycle-manager/go.mod
          cache-dependency-path: lifecycle-manager/go.sum
      - name: Create test clusters
        working-directory: lifecycle-manager
        run: |
          ./scripts/tests/create_test_clusters.sh \
            --k8s-version ${{ steps.configuration.outputs.k8s_version }} \
            --cert-manager-version ${{ steps.configuration.outputs.cert_manager_version }}
      - name: Deploy KLM from registry
        working-directory: lifecycle-manager
        run: |
          pushd config/watcher_local_test > /dev/null
          kustomize edit add patch --path patches/oci_registry_host.yaml --kind Deployment
          popd > /dev/null
          IMG="europe-docker.pkg.dev/kyma-project/dev/lifecycle-manager@sha256:14ffcac7339a22fa36fecf98ae686f1eb0461e9017c8a2af248a1120493972c4"
          for retry in $(seq 1 5); do
            if make local-deploy-with-watcher IMG="$IMG"; then
              kubectl wait pods -n kcp-system -l app.kubernetes.io/name=lifecycle-manager --for condition=Ready --timeout=20s && break
            fi
            echo "Retrying deploy ($retry/5)..."
            sleep 20
          done
      - name: Install k9s
        run: |
          curl -sL https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz | tar -xz -C /usr/local/bin k9s
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3
