name: TestSuite integration (local - single spec)

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  envtest-single-spec:
    name: "Run single integration spec"
    runs-on: ubuntu-latest
    env:
      GOSUMDB: sum.golang.org
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: lifecycle-manager
      - name: Get configuration
        uses: ./lifecycle-manager/.github/actions/get-configuration
        id: configuration
      - name: Setup tools
        uses: ./lifecycle-manager/.github/actions/setup-tools
        with:
          k8s_version: ${{ steps.configuration.outputs.k8s_version }}
          istio_version: ${{ steps.configuration.outputs.istio_version }}
          k3d_version: ${{ steps.configuration.outputs.k3d_version }}
          ocm_cli_version: ${{ steps.configuration.outputs.ocm_cli_version }}
          modulectl_version: ${{ steps.configuration.outputs.modulectl_version }}
          go-version-file: lifecycle-manager/go.mod
          cache-dependency-path: lifecycle-manager/go.sum
      - name: Create clusters and deploy KLM
        working-directory: lifecycle-manager
        env:
          KLM_IMAGE_REPO: dev
          KLM_VERSION_TAG: sha256:14ffcac7339a22fa36fecf98ae686f1eb0461e9017c8a2af248a1120493972c4
        run: |
          make -C tests/e2e create-clusters deploy-klm
      - name: Install k9s
        run: |
          curl -sL https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz | tar -xz -C /usr/local/bin k9s
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3
